# NT Quotations of the OT — Three-Way Text Comparison

This notebook demonstrates Feature #1: comparing how the NT quotes the OT against the original Hebrew (MT) and the LXX Greek.

**Data source:** OpenBible.info cross-references (CC-BY), distributed via scrollmapper.  
Each pair has a **vote score** reflecting community consensus on the strength of the connection:
- `votes >= 10` — possible allusion
- `votes >= 50` — probable quotation/strong allusion  
- `votes >= 100` — near-certain direct quotation

In [1]:
import sys
sys.path.insert(0, '../src')

import pandas as pd
pd.set_option('display.max_colwidth', 120)
pd.set_option('display.max_rows', 50)

from bible_grammar.quotations import (
    nt_quotations,
    verse_comparison,
    quotation_table,
    quotation_summary,
)

## 1. Overview: Which NT books quote the OT most?

In [2]:
summary = quotation_summary(min_votes=25)
print(f"NT books with at least one OT reference (votes >= 25): {len(summary)}")
summary

NT books with at least one OT reference (votes >= 25): 25

   nt_book  total_references  unique_nt_verses  unique_ot_verses top_ot_source
19     Mat               246                44                33           Psa
16     Jhn               148                40                37           Isa
23     Rom               131                33                40           Psa
14     Heb               127                20                34           Psa
18     Luk                96                34                27           Psa
5      2Co                90                15                32           Isa
12     Eph                76                18                31           Isa
15     Jas                59                14                26           Pro
0      1Co                58                18                25           Psa
22     Rev                57                16                22           Isa
2      1Pe                55                13                25           Psa
21     Php                43                 7                23           Psa
10     Act                42                21                25           Psa
20     Mrk                34                17                18           Isa
11     Col                23                12                17           Psa
13     Gal                23                 9                16           Pro
1      1Jn                21                 9                16           Psa
8      2Ti                21                 6                18           Psa
6      2Pe                13                 9                11           Psa
4      1Ti                 6                 4                 6           Ezk
3      1Th                 4                 2                 4           Job
24     Tit                 4                 4                 4           Isa
7      2Th                 3                 3                 3           Psa
9      3Jn                 1                 1                 1           Isa
17     Jud                 1                 1                 1           Zec

## 2. All high-confidence NT→OT quotations (votes >= 100)

In [3]:
high_conf = nt_quotations(min_votes=100)
print(f"High-confidence NT→OT references (votes >= 100): {len(high_conf)}")
high_conf[['nt_book','nt_chapter','nt_verse','ot_book','ot_chapter','ot_verse','votes']].head(20)

High-confidence NT→OT references (votes >= 100): 163

   nt_book  nt_chapter  nt_verse ot_book  ot_chapter  ot_verse  votes
0      Rom           8        29     Jer           1         5   1143
1      Php           4        13     Isa          41        10    905
2      Php           4        13     Isa          40        29    498
3      Mat          24        35     Isa          40         8    421
4      2Co           5        17     Ezk          36        26    383
5      Php           4         6     Pro           3         5    353
6      Mat           4         4     Deu           8         3    349
7      2Co           6        16     Exo          29        45    340
8      Heb           8        10     Ezk          36        26    321
9      Rom           8        28     Gen          50        20    320
10     Mat           6        33     Psa          34         9    312
11     Heb          13         6     Psa         118         6    299
12     1Co           2         9     Isa          64         4    298
13     1Pe           5         7     Psa          55        22    295
14     Jhn           1         1     Gen           1         1    276
15     Php           4        13     Isa          45        24    276
16     2Co           6        16     Lev          26        12    270
17     Mat          24        35     Num          23        19    269
18     Php           4         6     Psa          55        22    266
19     Rom           8        31     Psa         118         6    264

## 3. Three-Way Comparison: Matt 4:4 → Deut 8:3

Matthew's temptation narrative where Jesus quotes Deuteronomy 8:3.  
This is a direct citation — compare NT Greek, Hebrew MT, and LXX Greek.

In [4]:
t = quotation_table('Mat', 4, 4, min_votes=50)
t

,nt_ref,ot_ref,votes,nt_text,ot_text,lxx_text
0,Mat 4:4,Deu 8:3,349,"Ὁ δὲ ἀποκριθεὶς εἶπεν· γέγραπται· οὐκ ἐπ᾽ ἄρτῳ μόνῳ ζήσεται ὁ ἄνθρωπος, ἀλλ᾽ ἐπὶ παντὶ ῥήματι ἐκπορευομένῳ διὰ στόμα...",וַֽ/יְעַנְּ/ךָ֮ וַ/יַּרְעִבֶ/ךָ֒ וַ/יַּֽאֲכִֽלְ/ךָ֤ אֶת הַ/מָּן֙ אֲשֶׁ֣ר לֹא\־ יָדַ֔עְתָּ וְ/לֹ֥א יָדְע֖וּ/ן אֲבֹתֶ֑...,καὶ ἐκάκωσέν σε καὶ ἐλιμαγχόνησέν σε καὶ ἐψώμισέν σε τὸ μαννα ὃ οὐκ εἴδησαν οἱ πατέρες σου ἵνα ἀναγγείλῃ σοι ὅτι οὐκ...

## 4. Hebrews — the NT book most saturated with OT quotations

In [5]:
heb_refs = nt_quotations(nt_book='Heb', min_votes=50)
print(f"Hebrews NT→OT references (votes >= 50): {len(heb_refs)}")
heb_refs[['nt_chapter','nt_verse','ot_book','ot_chapter','ot_verse','votes']].head(20)

Hebrews NT→OT references (votes >= 50): 67

    nt_chapter  nt_verse ot_book  ot_chapter  ot_verse  votes
0            8        10     Ezk          36        26    321
1           13         6     Psa         118         6    299
2           13         6     Isa          41        10    261
3            8        10     Jer          31        33    247
4           13         6     Psa          27         1    216
5            8        10     Ezk          11        19    201
6            4        12     Jer          23        29    179
7           13         6     Psa         124         8    169
8            4        12     Isa          55        11    165
9           11         6     Pro           8        17    161
10           8        10     Deu          30         6    161
11           8        10     Jer          24         7    161
12          13         5     Deu          31         8    159
13          13         6     Psa          56         4    157
14          11         6     Jer          29        13    136
15           3         7     Psa          95         7    135
16          13         6     Psa          56        11    131
17          13         5     Jos           1         5    129
18          13         6     Psa          54         4    127
19          13         6     Psa          33        20    123

### Detailed comparison for Hebrews 1:5 (quoting Psalm 2:7 and 2 Sam 7:14)

In [6]:
t = quotation_table('Heb', 1, 5, min_votes=5)
t

,nt_ref,ot_ref,votes,nt_text,ot_text,lxx_text
0,Heb 1:5,Psa 2:7,61,"Τίνι γὰρ εἶπέν ποτε τῶν ἀγγέλων· υἱός μου εἶ σύ, ἐγὼ σήμερον γεγέννηκά σε; καὶ πάλιν· ἐγὼ ἔσομαι αὐτῷ εἰς πατέρα, κα...",אֲסַפְּרָ֗ה אֶֽ֫ל חֹ֥ק יְֽהוָ֗ה אָמַ֘ר אֵלַ֥/י בְּנִ֥/י אַ֑תָּה אֲ֝נִ֗י הַ/יּ֥וֹם יְלִדְתִּֽי/ךָ\׃,διαγγέλλων τὸ πρόσταγμα κυρίου κύριος εἶπεν πρός με υἱός μου εἶ σύ ἐγὼ σήμερον γεγέννηκά σε
1,Heb 1:5,2Sa 7:14,19,"Τίνι γὰρ εἶπέν ποτε τῶν ἀγγέλων· υἱός μου εἶ σύ, ἐγὼ σήμερον γεγέννηκά σε; καὶ πάλιν· ἐγὼ ἔσομαι αὐτῷ εἰς πατέρα, κα...",אֲנִי֙ אֶהְיֶה\־ לּ֣/וֹ לְ/אָ֔ב וְ/ה֖וּא יִהְיֶה\־ לִּ֣/י לְ/בֵ֑ן אֲשֶׁר֙ בְּ/הַ֣עֲוֹת֔/וֹ וְ/הֹֽכַחְתִּי/ו֙ בְּ/שֵׁ...,ἐγὼ ἔσομαι αὐτῷ εἰς πατέρα καὶ αὐτὸς ἔσται μοι εἰς υἱόν καὶ ἐὰν ἔλθῃ ἡ ἀδικία αὐτοῦ καὶ ἐλέγξω αὐτὸν ἐν ῥάβδῳ ἀνδρῶν...
2,Heb 1:5,1Ch 17:13,17,"Τίνι γὰρ εἶπέν ποτε τῶν ἀγγέλων· υἱός μου εἶ σύ, ἐγὼ σήμερον γεγέννηκά σε; καὶ πάλιν· ἐγὼ ἔσομαι αὐτῷ εἰς πατέρα, κα...",אֲנִי֙ אֶֽהְיֶה\־ לּ֣/וֹ לְ/אָ֔ב וְ/ה֖וּא יִֽהְיֶה\־ לִּ֣/י לְ/בֵ֑ן וְ/חַסְדִּ/י֙ לֹא\־ אָסִ֣יר מֵֽ/עִמּ֔/וֹ כַּ/אֲש...,ἐγὼ ἔσομαι αὐτῷ εἰς πατέρα καὶ αὐτὸς ἔσται μοι εἰς υἱόν καὶ τὸ ἔλεός μου οὐκ ἀποστήσω ἀπ᾿ αὐτοῦ ὡς ἀπέστησα ἀπὸ τῶν ...
3,Heb 1:5,1Ch 22:10,16,"Τίνι γὰρ εἶπέν ποτε τῶν ἀγγέλων· υἱός μου εἶ σύ, ἐγὼ σήμερον γεγέννηκά σε; καὶ πάλιν· ἐγὼ ἔσομαι αὐτῷ εἰς πατέρα, κα...",הֽוּא\־ יִבְנֶ֥ה בַ֙יִת֙ לִ/שְׁמִ֔/י וְ/הוּא֙ יִהְיֶה\־ לִּ֣/י לְ/בֵ֔ן וַ/אֲנִי\־ ל֖/וֹ לְ/אָ֑ב וַ/הֲכִ֨ינוֹתִ֜י כִּ...,οὗτος οἰκοδομήσει οἶκον τῷ ὀνόματί μου καὶ οὗτος ἔσται μοι εἰς υἱὸν κἀγὼ αὐτῷ εἰς πατέρα καὶ ἀνορθώσω θρόνον βασιλεί...
4,Heb 1:5,Psa 89:26,15,"Τίνι γὰρ εἶπέν ποτε τῶν ἀγγέλων· υἱός μου εἶ σύ, ἐγὼ σήμερον γεγέννηκά σε; καὶ πάλιν· ἐγὼ ἔσομαι αὐτῷ εἰς πατέρα, κα...",(no data),(no data)
5,Heb 1:5,1Ch 28:6,7,"Τίνι γὰρ εἶπέν ποτε τῶν ἀγγέλων· υἱός μου εἶ σύ, ἐγὼ σήμερον γεγέννηκά σε; καὶ πάλιν· ἐγὼ ἔσομαι αὐτῷ εἰς πατέρα, κα...",וַ/יֹּ֣אמֶר לִ֔/י שְׁלֹמֹ֣ה בִנְ/ךָ֔ הֽוּא\־ יִבְנֶ֥ה בֵיתִ֖/י וַ/חֲצֵרוֹתָ֑/י כִּי\־ בָחַ֨רְתִּי ב֥/וֹ לִ/י֙ לְ/בֵ֔...,καὶ εἶπέν μοι ὁ θεός Σαλωμων ὁ υἱός σου οἰκοδομήσει τὸν οἶκόν μου καὶ τὴν αὐλήν μου ὅτι ᾑρέτικα ἐν αὐτῷ εἶναί μου υἱ...

## 5. Isaiah — the most-quoted OT book in the NT

In [7]:
isa_refs = nt_quotations(ot_book='Isa', min_votes=50)
print(f"Isaiah NT→OT references (votes >= 50): {len(isa_refs)}")
isa_refs[['nt_book','nt_chapter','nt_verse','ot_chapter','ot_verse','votes']].head(20)

Isaiah NT→OT references (votes >= 50): 91

   nt_book  nt_chapter  nt_verse  ot_chapter  ot_verse  votes
0      Php           4        13          41        10    905
1      Php           4        13          40        29    498
2      Mat          24        35          40         8    421
3      1Co           2         9          64         4    298
4      Php           4        13          45        24    276
5      Heb          13         6          41        10    261
6      2Co           5        17          43        18    249
7      Mat          24        35          55        11    243
8      Luk           4        18          61         1    221
9      Gal           6         9          40        30    190
10     Mrk           7         6          29        13    180
11     Mat          24        35          51         6    176
12     Heb           4        12          55        11    165
13     Jhn           7        38          58        11    164
14     Mat          24        35          54        10    160
15     Jhn           7        38          44         3    160
16     Eph           5        14          60         1    150
17     Mat           1        23           7        14    144
18     2Co          12         9          40        29    141
19     Mrk           8        18           6         9    138

### Comparison for Rom 10:16 quoting Isa 53:1

In [8]:
t = quotation_table('Rom', 10, 16, min_votes=5)
t

,nt_ref,ot_ref,votes,nt_text,ot_text,lxx_text
0,Rom 10:16,Isa 53:1,19,"ἀλλ᾽ οὐ πάντες ὑπήκουσαν τῷ εὐαγγελίῳ· Ἠσαΐας γὰρ λέγει· κύριε, τίς ἐπίστευσεν τῇ ἀκοῇ ἡμῶν;",מִ֥י הֶאֱמִ֖ין לִ/שְׁמֻעָתֵ֑/נוּ וּ/זְר֥וֹעַ יְהוָ֖ה עַל\־ מִ֥י נִגְלָֽתָה\׃,κύριε τίς ἐπίστευσεν τῇ ἀκοῇ ἡμῶν καὶ ὁ βραχίων κυρίου τίνι ἀπεκαλύφθη

## 6. Word-level detail: verse_comparison()

For deeper analysis, `verse_comparison()` returns structured word lists for each side.

In [9]:
cmp = verse_comparison('Mat', 4, 4, min_votes=50)

print("=== NT (Matt 4:4) Greek words ===")
nt_df = pd.DataFrame(cmp['nt'])
display(nt_df)

for ref in cmp['refs']:
    print(f"\n=== OT source: {ref['ot_ref']} (votes={ref['votes']}) ===")
    print("Hebrew (MT):")
    display(pd.DataFrame(ref['ot_words']))
    print("LXX Greek:")
    display(pd.DataFrame(ref['lxx_words']))

=== NT (Matt 4:4) Greek words ===

,word,strongs,part_of_speech,conjugation,stem,person,number,gender
0,Ὁ,G3588,Article,,,,Singular,Masculine
1,δὲ,G1161,Conjunction,,,,,
2,ἀποκριθεὶς,G0611,Verb,,,,Singular,Masculine
3,εἶπεν·,G2036,Verb,,,3rd,Singular,
4,γέγραπται·,G1125,Verb,,,3rd,Singular,
5,οὐκ,G3756,Particle,,,,,
6,ἐπ᾽,G1909,Preposition,,,,,
7,ἄρτῳ,G0740,Noun,,,,Singular,Masculine
8,μόνῳ,G3441,Adjective,,,,Singular,Masculine
9,ζήσεται,G2198,Verb,,,3rd,Singular,
10,ὁ,G3588,Article,,,,Singular,Masculine
11,"ἄνθρωπος,",G0444,Noun,,,,Singular,Masculine
12,ἀλλ᾽,G0235,Conjunction,,,,,
13,ἐπὶ,G1909,Preposition,,,,,
14,παντὶ,G3956,Adjective,,,,Singular,Neuter
15,ῥήματι,G4487,Noun,,,,Singular,Neuter
16,ἐκπορευομένῳ,G1607,Verb,,,,Singular,Neuter
17,διὰ,G1223,Preposition,,,,,
18,στόματος,G4750,Noun,,,,Singular,Neuter
19,θεοῦ.¶,G2316,Noun,,,,Singular,Masculine

=== OT source: Deu 8:3 (votes=349) ===
Hebrew (MT):

                  word               strongs stem part_of_speech
0      וַֽ/יְעַנְּ/ךָ֮  H9001/{H6031B}/H9031              Suffix
1     וַ/יַּרְעִבֶ/ךָ֒   H9001/{H7456}/H9031              Suffix
2   וַ/יַּֽאֲכִֽלְ/ךָ֤   H9001/{H0398}/H9031              Suffix
3                  אֶת               {H0853}            Particle
4             הַ/מָּן֙        H9009/{H4478A}                Noun
5              אֲשֶׁ֣ר              {H0834A}            Particle
6                לֹא\־         {H3808}\H9014            Particle
7           יָדַ֔עְתָּ               {H3045}  Qal           Verb
8              וְ/לֹ֥א         H9002/{H3808}            Particle
9           יָדְע֖וּ/ן         {H3045}/H9013              Suffix
10         אֲבֹתֶ֑י/ךָ        {H0001G}/H9021              Suffix
11            לְמַ֣עַן               {H4616}            Particle
12        הוֹדִֽעֲ/ךָ֗         {H3045}/H9031              Suffix
13               כִּ֠י              {H3588A}            Particle
14                לֹ֣א               {H3808}            Particle
15               עַל\־        {H5921A}\H9014         Preposition
16          הַ/לֶּ֤חֶם        H9009/{H3899H}                Noun
17         לְ/בַדּ/וֹ֙  H9005/{H0905H}/H9033              Suffix
18            יִחְיֶ֣ה               {H2421}  Qal           Verb
19          הָֽ/אָדָ֔ם        H9009/{H0120G}                Noun
20               כִּ֛י              {H3588A}            Particle
21               עַל\־        {H5921A}\H9014         Preposition
22              כָּל\־         {H3605}\H9014                Noun
23             מוֹצָ֥א               {H4161}                Noun
24              פִֽי\־        {H6310G}\H9014                Noun
25             יְהוָ֖ה              {H3068G}                Noun
26            יִחְיֶ֥ה               {H2421}  Qal           Verb
27         הָ/אָדָֽם\׃  H9009/{H0120G}\H9016                Noun

LXX Greek:

,word,lemma,lemma_translit,strongs,part_of_speech,tense,voice,mood
0,καὶ,καί,kai,G2532,Conjunction,,,
1,ἐκάκωσέν,κακόω,kakoo,G2559,Verb,Aorist,Active,Indicative
2,σε,σέ,se,G4571,Pronoun,,,
3,καὶ,καί,kai,G2532,Conjunction,,,
4,ἐλιμαγχόνησέν,λιμαγχονέω,limagkhoneo,,Verb,Aorist,Active,Indicative
5,σε,σέ,se,G4571,Pronoun,,,
6,καὶ,καί,kai,G2532,Conjunction,,,
7,ἐψώμισέν,ψωμίζω,psomizo,G5595,Verb,Aorist,Active,Indicative
8,σε,σέ,se,G4571,Pronoun,,,
9,τὸ,ὁ,o,G3588,Article,,,
10,μαννα,μάννα,manna,G3131,Noun,,,
11,ὃ,ὅς,os,G3739,Pronoun,,,
12,οὐκ,οὐ,ou,G3756,Adverb,,,
13,εἴδησαν,ὁράω,orao,G3708,Verb,Aorist,Active,Indicative
14,οἱ,ὁ,o,G3588,Article,,,
15,πατέρες,πατήρ,pater,G3962,Noun,,,
16,σου,σοῦ,sou,G4675,Pronoun,,,
17,ἵνα,ἵνα,ina,G2443,Conjunction,,,
18,ἀναγγείλῃ,ἀναγγέλλω,anaggello,G312,Verb,Aorist,Active,Subjunctive
19,σοι,σοί,soi,G4671,Pronoun,,,
20,ὅτι,ὅτι,oti,G3754,Conjunction,,,
21,οὐκ,οὐ,ou,G3756,Adverb,,,
22,ἐπ᾿,ἐπί,epi,G1909,Preposition,,,
23,ἄρτῳ,ἄρτος,artos,G740,Noun,,,
24,μόνῳ,μόνος,monos,G3441,Adjective,,,
25,ζήσεται,ζάω,zao,G2198,Verb,Future,Middle,Indicative
26,ὁ,ὁ,o,G3588,Article,,,
27,ἄνθρωπος,ἄνθρωπος,anthropos,G444,Noun,,,
28,ἀλλ᾿,ἀλλά,alla,G235,Conjunction,,,
29,ἐπὶ,ἐπί,epi,G1909,Preposition,,,
30,παντὶ,πᾶς,pas,G3956,Adjective,,,
31,ῥήματι,ῥῆμα,Rema,G4487,Noun,,,
32,τῷ,ὁ,o,G3588,Article,,,
33,ἐκπορευομένῳ,ἐκπορεύομαι,ekporeuomai,G1607,Verb,Present,Middle,Participle
34,διὰ,διά,dia,G1223,Preposition,,,
35,στόματος,στόμα,stoma,G4750,Noun,,,
36,θεοῦ,θεός,theos,G2316,Noun,,,
37,ζήσεται,ζάω,zao,G2198,Verb,Future,Middle,Indicative
38,ὁ,ὁ,o,G3588,Article,,,
39,ἄνθρωπος,ἄνθρωπος,anthropos,G444,Noun,,,

## 7. How to query: quick reference

```python
# All NT→OT references with strong consensus
nt_quotations(min_votes=100)

# Quotations in Romans pointing to Psalms
nt_quotations(nt_book='Rom', ot_book='Psa', min_votes=25)

# Three-way text comparison for a specific verse
quotation_table('Heb', 2, 8, min_votes=5)   # returns DataFrame
verse_comparison('Heb', 2, 8, min_votes=5)  # returns dict with word lists

# Summary: how many OT quotes per NT book
quotation_summary(min_votes=50)

# Filter by NT book group
nt_quotations(nt_book=['Rom','Gal','Eph'], min_votes=25)
```