# Parallel Passage Viewer

Display any Bible passage with Hebrew MT | LXX Greek | KJV side by side, verse by verse.

- **OT passages**: Hebrew (TAHOT) | LXX Greek (CenterBLC) | KJV English
- **NT passages**: Greek (TAGNT) | KJV English
- **Cross-chapter ranges** supported
- **Word-level detail** available for individual verses

In [1]:
import sys
sys.path.insert(0, '../../../src')

import pandas as pd
pd.set_option('display.max_colwidth', 200)
pd.set_option('display.max_rows', 60)

from bible_grammar.parallel import parallel_passage, print_parallel, parallel_words

## 1. Genesis 1:1–5 — Creation Narrative

In [2]:
print_parallel('Gen', 1, 1, end_verse=5)

========================================================================
  Genesis 1:1–1:5
========================================================================

  Gen 1:1
  ----------------------------------------------------------------------
  HEB: בְּ/רֵאשִׁ֖ית בָּרָ֣א אֱלֹהִ֑ים אֵ֥ת הַ/שָּׁמַ֖יִם וְ/אֵ֥ת
       הָ/אָֽרֶץ\׃
  LXX: ἐν ἀρχῇ ἐποίησεν ὁ θεὸς τὸν οὐρανὸν καὶ τὴν γῆν
  KJV: In the beginning God created the heaven and the earth.

  Gen 1:2
  ----------------------------------------------------------------------
  HEB: וְ/הָ/אָ֗רֶץ הָיְתָ֥ה תֹ֙הוּ֙ וָ/בֹ֔הוּ וְ/חֹ֖שֶׁךְ עַל\־
       פְּנֵ֣י תְה֑וֹם וְ/ר֣וּחַ אֱלֹהִ֔ים מְרַחֶ֖פֶת עַל\־ פְּנֵ֥י
       הַ/מָּֽיִם\׃
  LXX: ἡ δὲ γῆ ἦν ἀόρατος καὶ ἀκατασκεύαστος καὶ σκότος ἐπάνω τῆς
       ἀβύσσου καὶ πνεῦμα θεοῦ ἐπεφέρετο ἐπάνω τοῦ ὕδατος
  KJV: And the earth was without form and void; and darkness was upon
       the face of the deep. And the Spirit of God moved upon the face
       of the waters.

  Gen 1:3
  ----------------------------------------------------------------------
  HEB: וַ/יֹּ֥אמֶר אֱלֹהִ֖ים יְהִ֣י א֑וֹר וַֽ/יְהִי\־ אֽוֹר\׃
  LXX: καὶ εἶπεν ὁ θεός γενηθήτω φῶς καὶ ἐγένετο φῶς
  KJV: And God said, Let there be light: and there was light.

  Gen 1:4
  ----------------------------------------------------------------------
  HEB: וַ/יַּ֧רְא אֱלֹהִ֛ים אֶת\־ הָ/א֖וֹר כִּי\־ ט֑וֹב וַ/יַּבְדֵּ֣ל
       אֱלֹהִ֔ים בֵּ֥ין הָ/א֖וֹר וּ/בֵ֥ין הַ/חֹֽשֶׁךְ\׃
  LXX: καὶ εἶδεν ὁ θεὸς τὸ φῶς ὅτι καλόν καὶ διεχώρισεν ὁ θεὸς ἀνὰ
       μέσον τοῦ φωτὸς καὶ ἀνὰ μέσον τοῦ σκότους
  KJV: And God saw the light, that it was good: and God divided the
       light from the darkness.

  Gen 1:5
  ----------------------------------------------------------------------
  HEB: וַ/יִּקְרָ֨א אֱלֹהִ֤ים\׀ לָ/אוֹר֙ י֔וֹם וְ/לַ/חֹ֖שֶׁךְ קָ֣רָא
       לָ֑יְלָה וַֽ/יְהִי\־ עֶ֥רֶב וַֽ/יְהִי\־ בֹ֖קֶר י֥וֹם אֶחָֽד\׃\
       \פ
  LXX: καὶ ἐκάλεσεν ὁ θεὸς τὸ φῶς ἡμέραν καὶ τὸ σκότος ἐκάλεσεν νύκτα
       καὶ ἐγένετο ἑσπέρα καὶ ἐγένετο πρωί ἡμέρα μία
  KJV: And God called the light Day, and the darkness he called Night.
       And the evening and the morning were the first day.

## 2. Isaiah 52:13–53:6 — The Suffering Servant

In [3]:
print_parallel('Isa', 52, 13, end_chapter=53, end_verse=6)

========================================================================
  Isaiah 52:13–53:6
========================================================================

  Isa 52:13
  ----------------------------------------------------------------------
  HEB: הִנֵּ֥ה יַשְׂכִּ֖יל עַבְדִּ֑/י יָר֧וּם וְ/נִשָּׂ֛א וְ/גָבַ֖הּ
       מְאֹֽד\׃
  LXX: ἰδοὺ συνήσει ὁ παῖς μου καὶ ὑψωθήσεται καὶ δοξασθήσεται σφόδρα
  KJV: Behold, my servant shall deal prudently, he shall be exalted
       and extolled, and be very high.

  Isa 52:14
  ----------------------------------------------------------------------
  HEB: כַּ/אֲשֶׁ֨ר שָׁמְמ֤וּ עָלֶ֙י/ךָ֙ רַבִּ֔ים כֵּן\־ מִשְׁחַ֥ת
       מֵ/אִ֖ישׁ מַרְאֵ֑/הוּ וְ/תֹאֲר֖/וֹ מִ/בְּנֵ֥י אָדָֽם\׃
  LXX: ὃν τρόπον ἐκστήσονται ἐπὶ σὲ πολλοί οὕτως ἀδοξήσει ἀπὸ ἀνθρώπων
       τὸ εἶδός σου καὶ ἡ δόξα σου ἀπὸ τῶν ἀνθρώπων
  KJV: As many were astonied at thee; his visage was so marred more
       than any man, and his form more than the sons of men:

  Isa 52:15
  ----------------------------------------------------------------------
  HEB: כֵּ֤ן יַזֶּה֙ גּוֹיִ֣ם רַבִּ֔ים עָלָ֛י/ו יִקְפְּצ֥וּ מְלָכִ֖ים
       פִּי/הֶ֑ם כִּ֠י אֲשֶׁ֨ר לֹֽא\־ סֻפַּ֤ר לָ/הֶם֙ רָא֔וּ
       וַ/אֲשֶׁ֥ר לֹֽא\־ שָׁמְע֖וּ הִתְבּוֹנָֽנוּ\׃
  LXX: οὕτως θαυμάσονται ἔθνη πολλὰ ἐπ᾿ αὐτῷ καὶ συνέξουσιν βασιλεῖς
       τὸ στόμα αὐτῶν ὅτι οἷς οὐκ ἀνηγγέλη περὶ αὐτοῦ ὄψονται καὶ οἳ
       οὐκ ἀκηκόασιν συνήσουσιν
  KJV: So shall he sprinkle many nations; the kings shall shut their
       mouths at him: for that which had not been told them shall they
       see; and that which they had not heard shall they consider.

  Isa 53:1
  ----------------------------------------------------------------------
  HEB: מִ֥י הֶאֱמִ֖ין לִ/שְׁמֻעָתֵ֑/נוּ וּ/זְר֥וֹעַ יְהוָ֖ה עַל\־ מִ֥י
       נִגְלָֽתָה\׃
  LXX: κύριε τίς ἐπίστευσεν τῇ ἀκοῇ ἡμῶν καὶ ὁ βραχίων κυρίου τίνι
       ἀπεκαλύφθη
  KJV: Who hath believed our report? and to whom is the arm of the
       Lord revealed?

  Isa 53:2
  ----------------------------------------------------------------------
  HEB: וַ/יַּ֨עַל כַּ/יּוֹנֵ֜ק לְ/פָנָ֗י/ו וְ/כַ/שֹּׁ֙רֶשׁ֙ מֵ/אֶ֣רֶץ
       צִיָּ֔ה לֹא\־ תֹ֥אַר ל֖/וֹ וְ/לֹ֣א הָדָ֑ר וְ/נִרְאֵ֥/הוּ
       וְ/לֹֽא\־ מַרְאֶ֖ה וְ/נֶחְמְדֵֽ/הוּ\׃
  LXX: ἀνηγγείλαμεν ἐναντίον αὐτοῦ ὡς παιδίον ὡς ῥίζα ἐν γῇ διψώσῃ οὐκ
       ἔστιν εἶδος αὐτῷ οὐδὲ δόξα καὶ εἴδομεν αὐτόν καὶ οὐκ εἶχεν
       εἶδος οὐδὲ κάλλος
  KJV: For he shall grow up before him as a tender plant, and as a
       root out of a dry ground: he hath no form nor comeliness; and
       when we shall see him, there is no beauty that we should desire
       him.

  Isa 53:3
  ----------------------------------------------------------------------
  HEB: נִבְזֶה֙ וַ/חֲדַ֣ל אִישִׁ֔ים אִ֥ישׁ מַכְאֹב֖וֹת וִ/יד֣וּעַ
       חֹ֑לִי וּ/כְ/מַסְתֵּ֤ר פָּנִים֙ מִמֶּ֔/נּוּ נִבְזֶ֖ה וְ/לֹ֥א
       חֲשַׁבְנֻֽ/הוּ\׃
  LXX: ἀλλὰ τὸ εἶδος αὐτοῦ ἄτιμον ἐκλεῖπον παρὰ πάντας ἀνθρώπους
       ἄνθρωπος ἐν πληγῇ ὢν καὶ εἰδὼς φέρειν μαλακίαν ὅτι ἀπέστραπται
       τὸ πρόσωπον αὐτοῦ ἠτιμάσθη καὶ οὐκ ἐλογίσθη
  KJV: He is despised and rejected of men; a man of sorrows, and
       acquainted with grief: and we hid as it were our faces from
       him; he was despised, and we esteemed him not.

  Isa 53:4
  ----------------------------------------------------------------------
  HEB: אָכֵ֤ן חֳלָיֵ֙/נוּ֙ ה֣וּא נָשָׂ֔א וּ/מַכְאֹבֵ֖י/נוּ סְבָלָ֑/ם
       וַ/אֲנַ֣חְנוּ חֲשַׁבְנֻ֔/הוּ נָג֛וּעַ מֻכֵּ֥ה אֱלֹהִ֖ים
       וּ/מְעֻנֶּֽה\׃
  LXX: οὗτος τὰς ἁμαρτίας ἡμῶν φέρει καὶ περὶ ἡμῶν ὀδυνᾶται καὶ ἡμεῖς
       ἐλογισάμεθα αὐτὸν εἶναι ἐν πόνῳ καὶ ἐν πληγῇ καὶ ἐν κακώσει
  KJV: Surely he hath borne our griefs, and carried our sorrows: yet
       we did esteem him stricken, smitten of God, and afflicted.

  Isa 53:5
  ----------------------------------------------------------------------
  HEB: וְ/הוּא֙ מְחֹלָ֣ל מִ/פְּשָׁעֵ֔/נוּ מְדֻכָּ֖א מֵ/עֲוֹנֹתֵ֑י/נוּ
       מוּסַ֤ר שְׁלוֹמֵ֙/נוּ֙ עָלָ֔י/ו וּ/בַ/חֲבֻרָת֖/וֹ נִרְפָּא\־
       לָֽ/נוּ\׃
  LXX: αὐτὸς δὲ ἐτραυματίσθη διὰ τὰς ἀνομίας ἡμῶν καὶ μεμαλάκισται διὰ
       τὰς ἁμαρτίας ἡμῶν παιδεία εἰρήνης ἡμῶν ἐπ᾿ αὐτόν τῷ μώλωπι
       αὐτοῦ ἡμεῖς ἰάθημεν
  KJV: But he was wounded for our transgressions, he was bruised for
       our iniquities: the chastisement of our peace was upon him; and
       with his stripes we are healed.

  Isa 53:6
  ----------------------------------------------------------------------
  HEB: כֻּלָּ֙/נוּ֙ כַּ/צֹּ֣אן תָּעִ֔ינוּ אִ֥ישׁ לְ/דַרְכּ֖/וֹ
       פָּנִ֑ינוּ וַֽ/יהוָה֙ הִפְגִּ֣יעַ בּ֔/וֹ אֵ֖ת עֲוֹ֥ן
       כֻּלָּֽ/נוּ\׃
  LXX: πάντες ὡς πρόβατα ἐπλανήθημεν ἄνθρωπος τῇ ὁδῷ αὐτοῦ ἐπλανήθη
       καὶ κύριος παρέδωκεν αὐτὸν ταῖς ἁμαρτίαις ἡμῶν
  KJV: All we like sheep have gone astray; we have turned every one to
       his own way; and the Lord hath laid on him the iniquity of us
       all.

## 3. Psalm 22:1–8 — "My God, my God" (quoted in the NT)

In [4]:
print_parallel('Psa', 22, 1, end_verse=8)

========================================================================
  Psalms 22:1–22:8
========================================================================

## 4. NT Passage: John 1:1–14 — The Prologue

In [5]:
print_parallel('Jhn', 1, 1, end_verse=14)

========================================================================
  John 1:1–1:14
========================================================================

  Jhn 1:1
  ----------------------------------------------------------------------
   GK: Ἐν ἀρχῇ ἦν ὁ λόγος, καὶ ὁ λόγος ἦν πρὸς τὸν θεόν, καὶ θεὸς ἦν
       ὁ λόγος.
  KJV: In the beginning was the Word, and the Word was with God, and
       the Word was God.

  Jhn 1:2
  ----------------------------------------------------------------------
   GK: οὗτος ἦν ἐν ἀρχῇ πρὸς τὸν θεόν.
  KJV: The same was in the beginning with God.

  Jhn 1:3
  ----------------------------------------------------------------------
   GK: πάντα δι᾽ αὐτοῦ ἐγένετο, καὶ χωρὶς αὐτοῦ ἐγένετο οὐδὲ ἓν ὃ
       γέγονεν.
  KJV: All things were made by him; and without him was not any thing
       made that was made.

  Jhn 1:4
  ----------------------------------------------------------------------
   GK: ἐν αὐτῷ ζωὴ ἦν, καὶ ἡ ζωὴ ἦν τὸ φῶς τῶν ἀνθρώπων,
  KJV: In him was life; and the life was the light of men.

  Jhn 1:5
  ----------------------------------------------------------------------
   GK: καὶ τὸ φῶς ἐν τῇ σκοτίᾳ φαίνει, καὶ ἡ σκοτία αὐτὸ οὐ
       κατέλαβεν.¶
  KJV: And the light shineth in darkness; and the darkness
       comprehended it not.

  Jhn 1:6
  ----------------------------------------------------------------------
   GK: Ἐγένετο ἄνθρωπος ἀπεσταλμένος παρὰ θεοῦ, ὄνομα αὐτῷ Ἰωάννης.
  KJV: There was a man sent from God, whose name was John.

  Jhn 1:7
  ----------------------------------------------------------------------
   GK: οὗτος ἦλθεν εἰς μαρτυρίαν ἵνα μαρτυρήσῃ περὶ τοῦ φωτός, ἵνα
       πάντες πιστεύσωσιν δι᾽ αὐτοῦ.
  KJV: The same came for a witness, to bear witness of the Light, that
       all men through him might believe.

  Jhn 1:8
  ----------------------------------------------------------------------
   GK: οὐκ ἦν ἐκεῖνος τὸ φῶς, ἀλλ᾽ ἵνα μαρτυρήσῃ περὶ τοῦ φωτός.
  KJV: He was not that Light, but was sent to bear witness of that
       Light.

  Jhn 1:9
  ----------------------------------------------------------------------
   GK: ἦν τὸ φῶς τὸ ἀληθινὸν ὃ φωτίζει πάντα ἄνθρωπον ἐρχόμενον εἰς
       τὸν κόσμον.
  KJV: That was the true Light, which lighteth every man that cometh
       into the world.

  Jhn 1:10
  ----------------------------------------------------------------------
   GK: ἐν τῷ κόσμῳ ἦν, καὶ ὁ κόσμος δι᾽ αὐτοῦ ἐγένετο, καὶ ὁ κόσμος
       αὐτὸν οὐκ ἔγνω.
  KJV: He was in the world, and the world was made by him, and the
       world knew him not.

  Jhn 1:11
  ----------------------------------------------------------------------
   GK: εἰς τὰ ἴδια ἦλθεν, καὶ οἱ ἴδιοι αὐτὸν οὐ παρέλαβον.
  KJV: He came unto his own, and his own received him not.

  Jhn 1:12
  ----------------------------------------------------------------------
   GK: ὅσοι δὲ ἔλαβον αὐτόν, ἔδωκεν αὐτοῖς ἐξουσίαν τέκνα θεοῦ
       γενέσθαι, τοῖς πιστεύουσιν εἰς τὸ ὄνομα αὐτοῦ,
  KJV: But as many as received him, to them gave he power to become
       the sons of God, even to them that believe on his name:

  Jhn 1:13
  ----------------------------------------------------------------------
   GK: οἳ οὐκ ἐξ αἱμάτων οὐδὲ ἐκ θελήματος σαρκὸς οὐδὲ ἐκ θελήματος
       ἀνδρὸς ἀλλ᾽ ἐκ θεοῦ ἐγεννήθησαν.
  KJV: Which were born, not of blood, nor of the will of the flesh,
       nor of the will of man, but of God.

  Jhn 1:14
  ----------------------------------------------------------------------
   GK: καὶ ὁ λόγος σὰρξ ἐγένετο καὶ ἐσκήνωσεν ἐν ἡμῖν, καὶ ἐθεασάμεθα
       τὴν δόξαν αὐτοῦ, δόξαν ὡς μονογενοῦς παρὰ πατρός, πλήρης
       χάριτος καὶ ἀληθείας.¶
  KJV: And the Word was made flesh, and dwelt among us, (and we beheld
       his glory, the glory as of the only begotten of the Father,)
       full of grace and truth.

## 5. DataFrame form — for further analysis

In [6]:
df = parallel_passage('Gen', 1, 1, end_verse=5)
df

,reference,hebrew,lxx,kjv
0,Gen 1:1,בְּ/רֵאשִׁ֖ית בָּרָ֣א אֱלֹהִ֑ים אֵ֥ת הַ/שָּׁמַ֖יִם וְ/אֵ֥ת הָ/אָֽרֶץ\׃,ἐν ἀρχῇ ἐποίησεν ὁ θεὸς τὸν οὐρανὸν καὶ τὴν γῆν,In the beginning God created the heaven and the earth.
1,Gen 1:2,וְ/הָ/אָ֗רֶץ הָיְתָ֥ה תֹ֙הוּ֙ וָ/בֹ֔הוּ וְ/חֹ֖שֶׁךְ עַל\־ פְּנֵ֣י תְה֑וֹם וְ/ר֣וּחַ אֱלֹהִ֔ים מְרַחֶ֖פֶת עַל\־ פְּנֵ֥י הַ/מָּֽיִם\׃,ἡ δὲ γῆ ἦν ἀόρατος καὶ ἀκατασκεύαστος καὶ σκότος ἐπάνω τῆς ἀβύσσου καὶ πνεῦμα θεοῦ ἐπεφέρετο ἐπάνω τοῦ ὕδατος,And the earth was without form and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.
2,Gen 1:3,וַ/יֹּ֥אמֶר אֱלֹהִ֖ים יְהִ֣י א֑וֹר וַֽ/יְהִי\־ אֽוֹר\׃,καὶ εἶπεν ὁ θεός γενηθήτω φῶς καὶ ἐγένετο φῶς,"And God said, Let there be light: and there was light."
3,Gen 1:4,וַ/יַּ֧רְא אֱלֹהִ֛ים אֶת\־ הָ/א֖וֹר כִּי\־ ט֑וֹב וַ/יַּבְדֵּ֣ל אֱלֹהִ֔ים בֵּ֥ין הָ/א֖וֹר וּ/בֵ֥ין הַ/חֹֽשֶׁךְ\׃,καὶ εἶδεν ὁ θεὸς τὸ φῶς ὅτι καλόν καὶ διεχώρισεν ὁ θεὸς ἀνὰ μέσον τοῦ φωτὸς καὶ ἀνὰ μέσον τοῦ σκότους,"And God saw the light, that it was good: and God divided the light from the darkness."
4,Gen 1:5,וַ/יִּקְרָ֨א אֱלֹהִ֤ים\׀ לָ/אוֹר֙ י֔וֹם וְ/לַ/חֹ֖שֶׁךְ קָ֣רָא לָ֑יְלָה וַֽ/יְהִי\־ עֶ֥רֶב וַֽ/יְהִי\־ בֹ֖קֶר י֥וֹם אֶחָֽד\׃\ \פ,καὶ ἐκάλεσεν ὁ θεὸς τὸ φῶς ἡμέραν καὶ τὸ σκότος ἐκάλεσεν νύκτα καὶ ἐγένετο ἑσπέρα καὶ ἐγένετο πρωί ἡμέρα μία,"And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day."

## 6. Word-level detail for a single verse

`parallel_words()` returns word-by-word tables with full morphology for both Hebrew MT and LXX.

In [7]:
pw = parallel_words('Gen', 1, 1)

print(f"=== {pw['reference']} ===")
print(f"KJV: {pw['kjv']}\n")

print("Hebrew (MT):")
display(pw['hebrew'])

print("LXX Greek:")
display(pw['lxx'])

=== Gen 1:1 ===
KJV: In the beginning God created the heaven and the earth.

Hebrew (MT):

,word_num,word,transliteration,translation,strongs,stem,conjugation,part_of_speech
0,1,בְּ/רֵאשִׁ֖ית,be./re.Shit,in/ beginning,H9003/{H7225G},,,Noun
1,2,בָּרָ֣א,ba.Ra',he created,{H1254A},Qal,Perfect,Verb
2,3,אֱלֹהִ֑ים,'E.lo.Him,God,{H0430G},,,Noun
3,4,אֵ֥ת,'et,<obj.>,{H0853},,,Particle
4,5,הַ/שָּׁמַ֖יִם,ha./sha.Ma.yim,the/ heavens,H9009/{H8064},,,Noun
5,6,וְ/אֵ֥ת,ve./'Et,and/ <obj.>,H9002/{H0853},,,Particle
6,7,הָ/אָֽרֶץ\׃,ha./'A.retz,the/ earth,H9009/{H0776G}\H9016,,,Noun

LXX Greek:

,word_num,word,transliteration,translation,lemma,lemma_translit,strongs,tense,voice,mood,part_of_speech
0,1,ἐν,en,in,ἐν,en,G1722,,,,Preposition
1,2,ἀρχῇ,archē,origin; beginning,ἀρχή,arkhe,G746,,,,Noun
2,3,ἐποίησεν,epoiēsen,do; make,ποιέω,poieo,G4160,Aorist,Active,Indicative,Verb
3,4,ὁ,ho,the,ὁ,o,G3588,,,,Article
4,5,θεὸς,theos,God,θεός,theos,G2316,,,,Noun
5,6,τὸν,ton,the,ὁ,o,G3588,,,,Article
6,7,οὐρανὸν,ouranon,sky; heaven,οὐρανός,ouranos,G3772,,,,Noun
7,8,καὶ,kai,and; even,καί,kai,G2532,,,,Conjunction
8,9,τὴν,tēn,the,ὁ,o,G3588,,,,Article
9,10,γῆν,gēn,earth; land,γῆ,ge,G1093,,,,Noun

In [8]:
# NT word-level — John 1:1
pw_nt = parallel_words('Jhn', 1, 1)

print(f"=== {pw_nt['reference']} ===")
print(f"KJV: {pw_nt['kjv']}\n")
print("Greek (NT):")
display(pw_nt['greek_nt'])

=== Jhn 1:1 ===
KJV: In the beginning was the Word, and the Word was with God, and the Word was God.

Greek (NT):

,word_num,word,transliteration,translation,strongs,tense,voice,mood,part_of_speech
0,1,Ἐν,,In [the],G1722,,,,Preposition
1,2,ἀρχῇ,,beginning,G0746,,,,Noun
2,3,ἦν,,was,G1510,Imperfect,Active,Indicative,Verb
3,4,ὁ,,the,G3588,,,,Article
4,5,"λόγος,",,"Word,",G3056,,,,Noun
5,6,καὶ,,and,G2532,,,,Conjunction
6,7,ὁ,,the,G3588,,,,Article
7,8,λόγος,,Word,G3056,,,,Noun
8,9,ἦν,,was,G1510,Imperfect,Active,Indicative,Verb
9,10,πρὸς,,with,G4314,,,,Preposition
10,11,τὸν,,<the>,G3588,,,,Article
11,12,"θεόν,",,"God,",G2316,,,,Noun
12,13,καὶ,,and,G2532,,,,Conjunction
13,14,θεὸς,,God,G2316,,,,Noun
14,15,ἦν,,was,G1510,Imperfect,Active,Indicative,Verb
15,16,ὁ,,the,G3588,,,,Article
16,17,λόγος.,,Word.,G3056,,,,Noun

## 7. With Vulgate

Add `include_vulgate=True` to include the Latin Vulgate Clementine as a fourth column.

In [9]:
print_parallel('Gen', 1, 1, end_verse=3, include_vulgate=True)

========================================================================
  Genesis 1:1–1:3
========================================================================

  Gen 1:1
  ----------------------------------------------------------------------
  HEB: בְּ/רֵאשִׁ֖ית בָּרָ֣א אֱלֹהִ֑ים אֵ֥ת הַ/שָּׁמַ֖יִם וְ/אֵ֥ת
       הָ/אָֽרֶץ\׃
  LXX: ἐν ἀρχῇ ἐποίησεν ὁ θεὸς τὸν οὐρανὸν καὶ τὴν γῆν
  KJV: In the beginning God created the heaven and the earth.
  VUL: In principio creavit Deus cælum et terram.

  Gen 1:2
  ----------------------------------------------------------------------
  HEB: וְ/הָ/אָ֗רֶץ הָיְתָ֥ה תֹ֙הוּ֙ וָ/בֹ֔הוּ וְ/חֹ֖שֶׁךְ עַל\־
       פְּנֵ֣י תְה֑וֹם וְ/ר֣וּחַ אֱלֹהִ֔ים מְרַחֶ֖פֶת עַל\־ פְּנֵ֥י
       הַ/מָּֽיִם\׃
  LXX: ἡ δὲ γῆ ἦν ἀόρατος καὶ ἀκατασκεύαστος καὶ σκότος ἐπάνω τῆς
       ἀβύσσου καὶ πνεῦμα θεοῦ ἐπεφέρετο ἐπάνω τοῦ ὕδατος
  KJV: And the earth was without form and void; and darkness was upon
       the face of the deep. And the Spirit of God moved upon the face
       of the waters.
  VUL: Terra autem erat inanis et vacua, et tenebræ erant super faciem
       abyssi : et spiritus Dei ferebatur super aquas.

  Gen 1:3
  ----------------------------------------------------------------------
  HEB: וַ/יֹּ֥אמֶר אֱלֹהִ֖ים יְהִ֣י א֑וֹר וַֽ/יְהִי\־ אֽוֹר\׃
  LXX: καὶ εἶπεν ὁ θεός γενηθήτω φῶς καὶ ἐγένετο φῶς
  KJV: And God said, Let there be light: and there was light.
  VUL: Dixitque Deus : Fiat lux. Et facta est lux.

## Quick Reference

```python
from bible_grammar.parallel import parallel_passage, print_parallel, parallel_words

# Console output
print_parallel('Gen', 1, 1, end_verse=5)                   # OT: HEB | LXX | KJV
print_parallel('Jhn', 1, 1, end_verse=18)                  # NT: GK | KJV
print_parallel('Isa', 53, 1, end_verse=12)                 # single chapter
print_parallel('Isa', 52, 13, end_chapter=53, end_verse=12) # cross-chapter
print_parallel('Gen', 1, 1, end_verse=3, include_vulgate=True) # add Vulgate
print_parallel('Gen', 1, 1, end_verse=5, include_lxx=False)    # no LXX

# DataFrame — for display in notebooks or further analysis
df = parallel_passage('Psa', 22, 1, end_verse=18)
df.columns   # reference, hebrew, lxx, kjv

# Word-level detail for a single verse
pw = parallel_words('Gen', 1, 1)    # OT
pw['hebrew']    # DataFrame: word, transliteration, translation, strongs, stem, ...
pw['lxx']       # DataFrame: word, lemma, lemma_translit, strongs, tense, voice, ...
pw['kjv']       # str

pw_nt = parallel_words('Rom', 8, 28)  # NT
pw_nt['greek_nt']  # DataFrame: word, transliteration, translation, strongs, tense, ...
```