# Word Study Tool

The `word_study` module produces a complete one-stop profile for any Hebrew or Greek lemma. For each Strong's number it combines:

- **Lexicon entry** — lemma, transliteration, gloss, and full definition from STEPBible's TBESH (Hebrew) or TBESG (Greek) lexicons
- **Total occurrences** and **distribution by book**
- **Morphological form inventory** — all stem/conjugation combinations used (Hebrew) or tense/voice/mood (Greek)
- **LXX translation equivalents** — which Greek lemmas the LXX uses to render this Hebrew word (OT only)
- **Example verses** with KJV English context

In [1]:
import sys
sys.path.insert(0, '../../../src')

import pandas as pd
pd.set_option('display.max_colwidth', 120)
pd.set_option('display.max_rows', 40)

from bible_grammar.wordstudy import word_study, print_word_study, word_study_table

## 1. Hebrew: בָּרָא (H1254) — "to create"

In [2]:
print_word_study('H1254')

=================================================================
  Word Study: H1254  —  Hebrew
=================================================================
  Lemma       : בָּרָא
  Translit    : ba.ra
  Gloss       : to create
  POS code    : H:V
  Occurrences : 48

  Definition:
    1) to create, shape, form1a) (Qal) to shape, fashion, create (always
    with God as subject)1a1) of heaven and earth1a2) of individual
    man1a3) of new conditions and circumstances1a4) of
    transformations1b) (Niphal) to be created1b1) of heaven and
    earth1b2) of birth1b3) of something new1b4) of miracles1c)
    (Piel)1c1) to cut down1c2) to cut out

  Distribution by Book (top 15):
    Genesis                11  ( 22.9%)  ███████████
    Exodus                  1  (  2.1%)  █
    Numbers                 1  (  2.1%)  █
    Deuteronomy             1  (  2.1%)  █
    Joshua                  2  (  4.2%)  ██
    1 Samuel                1  (  2.1%)  █
    2 Samuel                1  (  2.1%)  █
    Psalms                  2  (  4.2%)  ██
    Ecclesiastes            1  (  2.1%)  █
    Isaiah                 21  ( 43.8%)  █████████████████████
    Jeremiah                1  (  2.1%)  █
    Ezekiel                 3  (  6.2%)  ███
    Amos                    1  (  2.1%)  █
    Malachi                 1  (  2.1%)  █

  Morphological Forms (top 10):
  stem           conjugation part_of_speech state  count  pct
                                     Suffix           15 31.2
   Qal               Perfect           Verb           12 25.0
   Qal            Participle           Verb           11 22.9
Niphal               Perfect           Verb            3  6.2
   Qal   Consecutive Perfect           Verb            2  4.2
  Piel Consecutive Imperfect           Verb            1  2.1
  Piel  Infinitive construct           Verb            1  2.1
   Qal Consecutive Imperfect           Verb            1  2.1
   Qal             Imperfect           Verb            1  2.1
   Qal  Infinitive construct           Verb            1  2.1

  LXX Translation Equivalents (top 10):
lxx_lemma lxx_lemma_translit lxx_strongs     lxx_pos  count  pct
        ὁ                  o       G3588     Article    152 26.0
      καί                kai       G2532 Conjunction    116 19.9
    αὐτός              autos        G846     Pronoun     71 12.2
    ποιέω              poieo       G4160        Verb     43  7.4
     θεός              theos       G2316        Noun     28  4.8
      πᾶς                pas       G3956   Adjective     21  3.6
      ἐγώ                ego       G1473     Pronoun     20  3.4
       ἐν                 en       G1722 Preposition     20  3.4
     εἰμί               eimi       G1510        Verb     19  3.3
       οὐ                 ou       G3756      Adverb     18  3.1

  Example Verses:
    [Gen 1:1]  בָּרָ֣א
      In the beginning God created the heaven and the earth.
    [Gen 1:21]  וַ/יִּבְרָ֣א
      And God created great whales, and every living creature that moveth, which the waters b...
    [Gen 1:27]  וַ/יִּבְרָ֨א
      So God created man in his own image, in the image of God created he him; male and femal...
    [Gen 2:3]  בָּרָ֥א
      And God blessed the seventh day, and sanctified it: because that in it he had rested fr...
    [Gen 2:4]  בְּ/הִבָּֽרְאָ֑/ם
      These are the generations of the heavens and of the earth when they were created, in th...

## 2. Hebrew: כָּבוֹד (H3519) — "glory, honor"

In [3]:
print_word_study('H3519')

=================================================================
  Word Study: H3519  —  Hebrew
=================================================================
  Lemma       : כָּבוֹד
  Translit    : ka.vod
  Gloss       : glory
  POS code    : H:N-M
  Occurrences : 176

  Definition:
    1) glory, honour, glorious, abundance1a) abundance, riches1b)
    honour, splendour, glory1c) honour, dignity1d) honour, reputation1e)
    honour, reverence, glory1f) glory

  Distribution by Book (top 15):
    Genesis                 3  (  1.7%)
    Exodus                 11  (  6.2%)  ███
    Leviticus               2  (  1.1%)
    Numbers                 6  (  3.4%)  █
    Deuteronomy             1  (  0.6%)
    Joshua                  1  (  0.6%)
    1 Samuel                4  (  2.3%)  █
    1 Kings                 2  (  1.1%)
    1 Chronicles            6  (  3.4%)  █
    2 Chronicles           11  (  6.2%)  ███
    Nehemiah                1  (  0.6%)
    Esther                  2  (  1.1%)
    Job                     2  (  1.1%)
    Psalms                 31  ( 17.6%)  ████████
    Proverbs               16  (  9.1%)  ████

  Morphological Forms (top 10):
stem conjugation part_of_speech     state  count  pct
                           Noun  Absolute     66 37.5
                           Noun Construct     62 35.2
                         Suffix               48 27.3

  LXX Translation Equivalents (top 10):
lxx_lemma lxx_lemma_translit lxx_strongs     lxx_pos  count  pct
        ὁ                  o       G3588     Article    549 31.9
      καί                kai       G2532 Conjunction    373 21.7
    αὐτός              autos        G846     Pronoun    137  8.0
     δόξα               doxa       G1391        Noun    136  7.9
   κύριος             kurios       G2962        Noun     95  5.5
       ἐν                 en       G1722 Preposition     67  3.9
      ἐπί                epi       G1909 Preposition     62  3.6
      μου                mou       G3450     Pronoun     55  3.2
      εἰς                eis       G1519 Preposition     47  2.7
      πᾶς                pas       G3956   Adjective     42  2.4

  Example Verses:
    [Gen 31:1]  הַ/כָּבֹ֖ד
      And he heard the words of Laban’s sons, saying, Jacob hath taken away all that was our ...
    [Gen 45:13]  כְּבוֹדִ/י֙
      And ye shall tell my father of all my glory in Egypt, and of all that ye have seen; and...
    [Gen 49:6]  כְּבֹדִ֑/י
      O my soul, come not thou into their secret; unto their assembly, mine honour, be not th...
    [Exo 16:7]  כְּב֣וֹד
      And in the morning, then ye shall see the glory of the Lord; for that he heareth your m...
    [Exo 16:10]  כְּב֣וֹד
      And it came to pass, as Aaron spake unto the whole congregation of the children of Isra...

## 3. Greek NT: λόγος (G3056) — "word, reason"

In [4]:
print_word_study('G3056')

=================================================================
  Word Study: G3056  —  Greek
=================================================================
  Lemma       : λόγος
  Translit    : logos
  Gloss       : word
  POS code    : G:N-M
  Occurrences : 332

  Definition:
    λόγος, -ου, ὁ (λέγω) [in LXX chiefly for דָּבָר, also for מִלָּה
    ,אֵמֶר, etc. ;] __I. Of that by which the inward thought is
    expressed, Lat. oratio, sermo, vox, verbum. __1. a word, not in the
    grammatical sense of a mere name (ἔπος, ὄνομα, ῥῆμα), but a word as
    embodying a conception or idea: Mat.8:8, Luk.7:7, 1Co.14:9, 19
    Heb.12:19, al. __2. a saying, statement, declaration: Mat.19:22 (T
    om.), Mrk.5:36 7:29, Luk.1:29, Jhn.2:22 6:60, Act.7:29, al.; with
    genitive attrib., Act.13:15, Rom.9:9, Heb.7:28, al.; of the sayings,
    commands, promises, etc., of teachers, Mat.7:24 10:14, Mrk.8:38,
    Luk.9:4, Jhn.14:24, al.; λ. κενοί, Eph.5:6; ἀληθινοί, Rev.19:9;
    πιστοί, Rev.22:6; esp. of the precepts, decrees and promises of God,
    ὁ λ. τ. θεοῦ, the word of God: Mrk.7:13, Jhn.10:35, Rom.13:9,
    1Co.14:36, Php.1:14, al.; absol., ὁ λ., Mat.13:21, 22 Mrk.16:[20],
    Luk.1:2, Act.6:4, Heb.4:12, al. __3. speech, discourse: Act.14:12,
    2Co.10:10, Jas.3:2; opposite to ἐπιστολή, 2Th.2:15; disting, from
    σοφία, 1Co.2:1; ἀναστροφή, 1Ti.4:12; δύναμις, 1Co.4:19, 1Th.1:5;
    ἔργον, Rom.15:18; οὐδενὸς λ. τίμιον (not worthy of mention),
    Act.20:24; of the faculty of speech, Luk.24:19, 2Co.11:6; of the
    style of speech, Mat.5:37, 1Co.1:5; of instruction, Col.4:3,
    1Pe.3:1; with genitive of person(s), Jhn.5:24 8:52, Act.2:41, al.; ὁ
    λ. ὁ ἐμός, Jhn.8:31; with genitive obj. (τ.) ἀληθείας, 2Co.6:7,
    Col.1:5, Jas.1:18; τ. καταλλαγῆς, 2Co.5:19; τ. σταυροῦ, 1Co.1:18; of
    mere talk, 1Co.4:19, 2o, Col.2:23, 1Jn.3:18; of the talk which one
    occasions, hence, repute: Col.2:23. __4. subject-matter, hence,
    teaching, doctrine: Act.18:15, 2Ti.2:17, al.; esp. of Christian
    doctrine: Mat.13:20-23, Mrk.4:14-20 8:32, Luk.1:2, Act.8:4, Gal.6:6,
    1Th.1:6, al.; with genitive of person(s), τ. θεοῦ, Luk.5:1,
    Jhn.17:6, Act.4:29, 1Co.14:36, I Jhn.1:10, Rev.6:9, al.; τ. Κυρίου,
    Act.8:25, 1Th.1:8, al.; τ. Χριστοῦ, Col.3:16, Rev.3:8; with genitive
    appos., Act.15:7; with genitive attrib., Heb.5:13. __5. a story,
    tale, narrative: Mat.28:15, Jhn.21:23, Act.1:1 11:22; before περί,
    Luk.5:15. __6. That which is spoken of (Plat., al.; V. Kennedy,
    Sources, 124), matter, affair, thing: Mat.21:24, Mrk.1:45 11:29,
    Luk.20:3, Act.8:21; of a matter in dispute, as a case or suit at
    law, Act.19:38; pl. (1Ma.7:33, al.), Luk.1:4. __II. Of the inward
    thought itself, Lat. ratio. __1. reason, __(a) of the mental faculty
    (Hdt., Plat., al.): κατὰ λόγον, Act.18:14; __(b) a reason, cause:
    τίνι λόγῳ, Act.10:29; παρεκτὸς λόγου πορνείας, Mat.5:32 19:9, WH,
    mg., R, mg. __2. account, __(a) regard: Act.20:24, Rec.; __(b)
    reckoning: Php.4:15, 17; συναίρειν (which see) λ., Mat.18:23 25:19;
    in forensic sense, Rom.14:12, Heb.13:17, 1Pe.4:5; with genitive of
    thing(s), Luk.16:2; before περί, Mat.12:36, Act.19:40, 1Pe.3:15.
    __3. proportion, analogy: Php.2:16 (Field, Notes, 193 f.). __III. ὁ
    λ., the Divine Word or Logos: Jhn.1:1, 14; τ. ζωῆς, 1Jn.1:1; τ.
    θεοῦ, Rev.19:13 (see Westc, Swete, CGT, in ll.; reff. in Artt.,
    Logos, DB, DCG). (AS)

  Distribution by Book (top 15):
    Matthew                33  (  9.9%)  ████
    Mark                   24  (  7.2%)  ███
    Luke                   32  (  9.6%)  ████
    John                   40  ( 12.0%)  ██████
    Acts                   65  ( 19.6%)  █████████
    Romans                  8  (  2.4%)  █
    1 Corinthians          17  (  5.1%)  ██
    2 Corinthians           9  (  2.7%)  █
    Galatians               2  (  0.6%)
    Ephesians               4  (  1.2%)
    Philippians             4  (  1.2%)
    Colossians              7  (  2.1%)  █
    1 Thessalonians         9  (  2.7%)  █
    2 Thessalonians         5  (  1.5%)
    1 Timothy               8  (  2.4%)  █

  Morphological Forms (top 10):
tense voice mood part_of_speech  count   pct
                           Noun    332 100.0

  Example Verses:
    [Mat 5:32]  λόγου
      But I say unto you, That whosoever shall put away his wife, saving for the cause of for...
    [Mat 5:37]  λόγος
      But let your communication be, Yea, yea; Nay, nay: for whatsoever is more than these co...
    [Mat 7:24]  λόγους
      Therefore whosoever heareth these sayings of mine, and doeth them, I will liken him unt...
    [Mat 7:26]  λόγους
      And every one that heareth these sayings of mine, and doeth them not, shall be likened ...
    [Mat 7:28]  λόγους
      And it came to pass, when Jesus had ended these sayings, the people were astonished at ...

## 4. Greek NT: πίστις (G4102) — "faith, belief"

In [5]:
print_word_study('G4102')

=================================================================
  Word Study: G4102  —  Greek
=================================================================
  Lemma       : πίστις
  Translit    : pistis
  Gloss       : faith
  POS code    : G:N-F
  Occurrences : 242

  Definition:
    πίστις, -εως, ἡ (πείθω), [in LXX chiefly for אֱמוּנָה ;] __1. in
    active sense, faith, belief, trust, confidence, in NT always of
    religious faith in God or Christ or spiritual things: Mat.8:10,
    Luk.5:20, Act.14:9, Rom.1:8, 1Co.2:5, 2Co.1:24, 1Ti.1:5, al.; with
    genitive obj., Mrk.11:22, Act.3:16, Rom.3:22, Gal.2:16, Eph.3:12,
    Jas.2:1, al.; with prep., ἐν, Rom.3:25, Gal.3:26, Eph.1:15,
    Col.1:24, 1Ti.1:14 3:13, 2Ti.1:13 3:15, 2Pe.1:1; εἰς, Act.20:21
    24:24 26:18, Col.2:5, 1Pe.1:21; πρός, 1Th.1:8, Phm 5; ἐπί, with
    accusative Heb.6:1; ἐν τῇ π. στήκειν (εἶναι, μένειν), 1Co.16:13,
    1Co.13:5, 1Ti.2:15; ὑπακοὴ τῆς π., Rom.1:5 16:26; ὁ ἐκ π., Rom.3:26
    4:16, Gal.3:12; διὰ (τῆς) π., Rom.3:30, Gal.2:16, Php.3:9. By
    meton., objectively, that which is the object or content of belief,
    the faith: Act.6:7 14:22, Gal.1:23 3:23 6:10, Php.1:26, 27 Ju 3, 20,
    and perh. also Act.13:8 16:5, Rom.1:5 and 16:26 (see supr.),
    1Co.16:13, Col.1:23, 2Th.3:2 (Lft., Notes, 125), 1Ti.1:19 3:9 4:1, 6
    5:8 6:10, 12, 2Ti.3:8 4:7 Tit.1:4, 13 3:15, 1Pe.5:9. __2. In passive
    sense, __(a) fidelity, faithfulness: Mat.23:23, Gal.5:22; ἡ π. τοῦ
    θεοῦ, Rom.3:3; __(b) objectively, plighted faith, a pledge of
    fidelity: 1Ti.5:12. (On the various shades of meaning in which the
    word is used in NT, see esp. ICC on Rom.1:17, pp. 31ff.; Lft., Ga.,
    154ff.; Stevens, Th. NT, 422, 515ff.; DB, i, 830ff.; Cremer, see
    word) (AS)

  Distribution by Book (top 15):
    Matthew                 8  (  3.3%)  █
    Mark                    5  (  2.1%)  █
    Luke                   11  (  4.5%)  ██
    Acts                   15  (  6.2%)  ███
    Romans                 39  ( 16.1%)  ████████
    1 Corinthians           7  (  2.9%)  █
    2 Corinthians           7  (  2.9%)  █
    Galatians              22  (  9.1%)  ████
    Ephesians               8  (  3.3%)  █
    Philippians             5  (  2.1%)  █
    Colossians              5  (  2.1%)  █
    1 Thessalonians         8  (  3.3%)  █
    2 Thessalonians         5  (  2.1%)  █
    1 Timothy              19  (  7.9%)  ███
    2 Timothy               8  (  3.3%)  █

  Morphological Forms (top 10):
tense voice mood part_of_speech  count   pct
                           Noun    242 100.0

  Example Verses:
    [Mat 8:10]  πίστιν
      When Jesus heard it, he marvelled, and said to them that followed, Verily I say unto yo...
    [Mat 9:2]  πίστιν
      And, behold, they brought to him a man sick of the palsy, lying on a bed: and Jesus see...
    [Mat 9:22]  πίστις
      But Jesus turned him about, and when he saw her, he said, Daughter, be of good comfort;...
    [Mat 9:29]  πίστιν
      Then touched he their eyes, saying, According to your faith be it unto you.
    [Mat 15:28]  πίστις·
      Then Jesus answered and said unto her, O woman, great is thy faith: be it unto thee eve...

## 5. Programmatic access: word_study() returns a dict

In [6]:
ws = word_study('H1254')

print(f"Lemma: {ws['lemma']}  ({ws['translit']})")
print(f"Gloss: {ws['gloss']}")
print(f"Total occurrences: {ws['total_occurrences']}")
print()
print("Distribution by book:")
display(ws['by_book'])
print("\nMorphological forms:")
display(ws['morphological_forms'])
print("\nLXX translation equivalents (top 10 — filtered to Verbs):")
from bible_grammar.alignment import translation_equivalents
display(translation_equivalents(heb_strongs='H1254', lxx_pos='Verb', top_n=10))

Lemma: בָּרָא  (ba.ra)
Gloss: to create
Total occurrences: 48

Distribution by book:

   book_id     book_name  count   pct
0      Gen       Genesis     11  22.9
1      Exo        Exodus      1   2.1
2      Num       Numbers      1   2.1
3      Deu   Deuteronomy      1   2.1
4      Jos        Joshua      2   4.2
5      1Sa      1 Samuel      1   2.1
6      2Sa      2 Samuel      1   2.1
7      Psa        Psalms      2   4.2
8      Ecc  Ecclesiastes      1   2.1
9      Isa        Isaiah     21  43.8
10     Jer      Jeremiah      1   2.1
11     Ezk       Ezekiel      3   6.2
12     Amo          Amos      1   2.1
13     Mal       Malachi      1   2.1

Morphological forms:

     stem            conjugation part_of_speech state  count   pct
0                                        Suffix           15  31.2
1     Qal                Perfect           Verb           12  25.0
2     Qal             Participle           Verb           11  22.9
3  Niphal                Perfect           Verb            3   6.2
4     Qal    Consecutive Perfect           Verb            2   4.2
5    Piel  Consecutive Imperfect           Verb            1   2.1
6    Piel   Infinitive construct           Verb            1   2.1
7     Qal  Consecutive Imperfect           Verb            1   2.1
8     Qal              Imperfect           Verb            1   2.1
9     Qal   Infinitive construct           Verb            1   2.1

LXX translation equivalents (top 10 — filtered to Verbs):

      lxx_lemma lxx_lemma_translit lxx_strongs lxx_pos  count   pct
0         ποιέω              poieo       G4160    Verb     43  33.9
1          εἰμί               eimi       G1510    Verb     19  15.0
2            οὐ                 ou       G3756  Adverb     18  14.2
3         κτίζω              ktizo       G2936    Verb     14  11.0
4       γίνομαι            ginomai       G1096    Verb      8   6.3
5           ἔπω                epo       G2036    Verb      6   4.7
6            μή                 me       G3361  Adverb      6   4.7
7  καταδείκνυμι       katadeiknumi                Verb      5   3.9
8          λέγω               lego       G3004    Verb      4   3.1
9   κατασκευάζω        kataskeuazo       G2680    Verb      4   3.1

## 6. Tabular concordance form

`word_study_table()` returns every occurrence as a DataFrame row — equivalent to `concordance()` but with the lexicon gloss attached.

In [7]:
tbl = word_study_table('H1254')
print(f"Lemma: {tbl.attrs.get('lemma', '')}  —  {tbl.attrs.get('gloss', '')}")
tbl[['reference', 'word', 'stem', 'conjugation', 'context_text']]

Lemma: בָּרָא  —  to create

,reference,word,stem,conjugation,context_text
0,Gen 1:1,בָּרָ֣א,Qal,Perfect,In the beginning God created the heaven and the earth.
1,Gen 1:21,וַ/יִּבְרָ֣א,Qal,Consecutive Perfect,"And God created great whales, and every living creature that moveth, which the waters brought forth abundantly, afte..."
2,Gen 1:27,וַ/יִּבְרָ֨א,Qal,Consecutive Perfect,"So God created man in his own image, in the image of God created he him; male and female created he them."
3,Gen 1:27,בָּרָ֣א,Qal,Perfect,"So God created man in his own image, in the image of God created he him; male and female created he them."
4,Gen 1:27,בָּרָ֥א,Qal,Perfect,"So God created man in his own image, in the image of God created he him; male and female created he them."
...,...,...,...,...,...
43,Ezk 23:47,וּ/בָרֵ֥א,Piel,Infinitive construct,"And the company shall stone them with stones, and dispatch them with their swords; they shall slay their sons and th..."
44,Ezk 28:13,הִבָּרַאֲ/ךָ֖,,,"Thou hast been in Eden the garden of God; every precious stone was thy covering, the sardius, topaz, and the diamond..."
45,Ezk 28:15,הִבָּֽרְאָ֑/ךְ,,,"Thou wast perfect in thy ways from the day that thou wast created, till iniquity was found in thee."
46,Amo 4:13,וּ/בֹרֵ֣א,Qal,Participle,"For, lo, he that formeth the mountains, and createth the wind, and declareth unto man what is his thought, that make..."
47,Mal 2:10,בְּרָאָ֑/נוּ,,,"Have we not all one father? hath not one God created us? why do we deal treacherously every man against his brother,..."

## Quick Reference

```python
from bible_grammar.wordstudy import word_study, print_word_study, word_study_table

# Formatted output to console
print_word_study('H1254')    # Hebrew: בָּרָא "to create"
print_word_study('H3519')    # Hebrew: כָּבוֹד "glory"
print_word_study('H8451')    # Hebrew: תּוֹרָה "law, instruction"
print_word_study('G3056')    # Greek: λόγος "word"
print_word_study('G4102')    # Greek: πίστις "faith"
print_word_study('G26')      # Greek: ἀγάπη "love"
print_word_study('G5547')    # Greek: Χριστός "Christ"

# Get dict for programmatic access
ws = word_study('H8451')
ws['lemma']                  # תּוֹרָה
ws['gloss']                  # "law, instruction"
ws['definition']             # full BDB/LSJ definition
ws['total_occurrences']      # int
ws['by_book']                # DataFrame: book_id, book_name, count, pct
ws['morphological_forms']    # DataFrame: stem/conjugation or tense/voice/mood
ws['translation_equivalents'] # DataFrame: LXX Greek lemmas (Hebrew only)
ws['examples']               # list of {reference, word, context} dicts

# Full concordance with lexicon gloss attached
word_study_table('G4102')    # all πίστις occurrences
```