# Biblical Language Analysis — Feature Showcase

This notebook demonstrates the language analysis features added to `bible_grammar`
beyond the basic morphology query API:

| # | Feature | Module |
|---|---|---|
| 1 | [Semantic Profile](#1-semantic-profile) | `semantic_profile` |
| 2 | [Synonym Comparison](#2-synonym-comparison) | `synonym` |
| 3 | [LXX Translation Consistency](#3-lxx-translation-consistency) | `lxx_consistency` |
| 4 | [NT Quotation Word Alignment](#4-nt-quotation-word-alignment) | `quotation_align` |
| 5 | [Theological Term Map](#5-theological-term-map) | `termmap` |
| 6 | [Phrase & Proximity Search](#6-phrase--proximity-search) | `phrase` |
| 7 | [Collocation Statistics](#7-collocation-statistics) | `collocation` |
| 8 | [Morphological Distribution Charts](#8-morphological-distribution-charts) | `morph_chart` |

**Export as shareable HTML:**
```bash
jupyter nbconvert --to html notebooks/09_language_analysis.ipynb
```

In [1]:
import sys
sys.path.insert(0, '../../../src')

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
pd.set_option('display.max_rows', 60)
pd.set_option('display.max_columns', 20)
pd.set_option('display.width', 120)

print('Ready.')

Ready.

---
## 1. Semantic Profile

The `semantic_profile` module produces a complete one-stop analysis for any Hebrew or Greek root,
combining lexicon data, corpus frequency, morphological breakdown, LXX equivalents,
OT→LXX→NT trajectory, collocations, and example verses.

**Examples below:** שָׁלוֹם (H7965 *peace*) and λόγος (G3056 *word*)

In [2]:
from bible_grammar.semantic_profile import print_semantic_profile

print_semantic_profile('H7965')  # שָׁלוֹם peace

══════════════════════════════════════════════════════════════════════
  Semantic Profile: H7965  —  Hebrew
  שָׁלוֹם  /sha.lom/
  Gloss: peace
══════════════════════════════════════════════════════════════════════

  Definition
  ----------------------------------------------------------------------
    : peace1) completeness, soundness, welfare, peace1a) completeness
    (in number)1b) safety, soundness (in body)1c) welfare, health,
    prosperity1d) peace, quiet, tranquillity, contentment1e) peace,
    friendship1e1) of human relationships1e2) with God especially in
    covenant relationship1f) peace (from war)1g) peace (as adjective)

  Frequency                                  237 occurrences
  ----------------------------------------------------------------------
    Genesis                   15  ( 6.3%)  ███
    Exodus                     3  ( 1.3%)
    Leviticus                  1  ( 0.4%)
    Numbers                    2  ( 0.8%)
    Deuteronomy                5  ( 2.1%)  █
    Joshua                     2  ( 0.8%)
    Judges                    10  ( 4.2%)  ██
    1 Samuel                  18  ( 7.6%)  ███
    2 Samuel                  16  ( 6.8%)  ███
    1 Kings                   11  ( 4.6%)  ██
    2 Kings                   20  ( 8.4%)  ████
    1 Chronicles               6  ( 2.5%)  █
    … and 19 more books

  Morphological Distribution
  ----------------------------------------------------------------------
    Noun                                  210  (88.6%)  █████████████████████████
    Suffix                                 10  ( 4.2%)  ██

  LXX Translation Equivalents
  ----------------------------------------------------------------------
    εἰρήνη               G1515        116  (100.0%)  ████████████████████

  LXX Consistency: 100%  (primary: εἰρήνη  100%)

  OT → LXX → NT Trajectory
  ----------------------------------------------------------------------
    εἰρήνη               (G1515)  →  92 NT occurrences
      Mat             4
      Mrk             1
      Luk            14
      Jhn             6
      Act             7
      Rom            11

  Top Collocates  (window ±5, corpus OT)
  ----------------------------------------------------------------------
    Lemma                  Gloss                       Obs        G²
    --------------------- ------------------------ -----  --------
    אָמַר                  to say                      116     124.9
    אֵת                    [Obj.]                       33      57.6
    אַ֫יִן                 nothing                      31      54.4
    שָׁאַל                 to ask                       16      52.6
    יֵהוּא                 Jehu                          9      38.5
    קָרָא                  to encounter: meet           11      32.4
    אֱמֶת                  truth: faithful              10      29.3
    לַ֫חַץ                 oppression                    4      23.8
    שׁוּב                  to return: return            24      21.3
    מַרְפֵּא               healing                       4      21.1

  Example Verses
  ----------------------------------------------------------------------
    [Gen 15:15]  בְּ/שָׁל֑וֹם
      And thou shalt go to thy fathers in peace; thou shalt be buried in a good old age.
    [Gen 26:29]  בְּ/שָׁל֑וֹם
      That thou wilt do us no hurt, as we have not touched thee, and as we have done unto t...
    [Gen 26:31]  בְּ/שָׁלֽוֹם\׃
      And they rose up betimes in the morning, and sware one to another: and Isaac sent the...
    [Gen 28:21]  בְ/שָׁל֖וֹם
      So that I come again to my father’s house in peace; then shall the Lord be my God:

In [3]:
print_semantic_profile('G3056')  # λόγος word

══════════════════════════════════════════════════════════════════════
  Semantic Profile: G3056  —  Greek
  λόγος  /logos/
  Gloss: word
══════════════════════════════════════════════════════════════════════

  Definition
  ----------------------------------------------------------------------
    λόγος, -ου, ὁ (λέγω) [in LXX chiefly for דָּבָר, also for מִלָּה
    ,אֵמֶר, etc. ;] __I. Of that by which the inward thought is
    expressed, Lat. oratio, sermo, vox, verbum. __1. a word, not in
    the grammatical sense of a mere name (ἔπος, ὄνομα, ῥῆμα), but a
    word as embodying a conception or idea: Mat.8:8, Luk.7:7,
    1Co.14:9, 19 Heb.12:19, al. __2. a saying, statement, declaration:
    Mat.19:22 (T om.), Mrk.5:36 7:29, Luk.1:29, Jhn.2:22 6:60,
    Act.7:29, al.; with genitive attrib., Act.13:15, Rom.9:9,
    Heb.7:28, al.; of the sayings, commands, promises, etc., of
    teachers, Mat.7:24 10:14, Mrk.8:38, Luk.9:4, Jhn.14:24, al.; λ.
    κενοί, Eph.5:6; ἀληθινοί, Rev.19:9; πιστοί, Rev.22:6; esp. of the
    precepts, decrees and promises of God, ὁ λ. τ. θεοῦ, the word of
    God: Mrk.7:13, Jhn.10:35, Rom.13:9, 1Co.14:36, Php.1:14, al.;
    absol., ὁ λ., Mat.13:21, 22 Mrk.16:[20], Luk.1:2, Act.6:4,
    Heb.4:12, al. __3. speech, discourse: Act.14:12, 2Co.10:10,
    Jas.3:2; opposite to ἐπιστολή, 2Th.2:15; disting, from σοφία,
    1Co.2:1; ἀναστροφή, 1Ti.4:12; δύναμις, 1Co.4:19, 1Th.1:5; ἔργον,
    Rom.15:18; οὐδενὸς λ. τίμιον (not worthy of mention), Act.20:24;
    of the faculty of speech, Luk.24:19, 2Co.11:6; of the style of
    speech, Mat.5:37, 1Co.1:5; of instruction, Col.4:3, 1Pe.3:1; with
    genitive of person(s), Jhn.5:24 8:52, Act.2:41, al.; ὁ λ. ὁ ἐμός,
    Jhn.8:31; with genitive obj. (τ.) ἀληθείας, 2Co.6:7, Col.1:5,
    Jas.1:18; τ. καταλλαγῆς, 2Co.5:19; τ. σταυροῦ, 1Co.1:18; of mere
    talk, 1Co.4:19, 2o, Col.2:23, 1Jn.3:18; of the talk which one
    occasions, hence, repute: Col.2:23. __4. subject-matter, hence,
    teaching, doctrine: Act.18:15, 2Ti.2:17, al.; esp. of Christian
    doctrine: Mat.13:20-23, Mrk.4:14-20 8:32, Luk.1:2, Act.8:4,
    Gal.6:6, 1Th.1:6, al.; with genitive of person(s), τ. θεοῦ,
    Luk.5:1, Jhn.17:6, Act.4:29, 1Co.14:36, I Jhn.1:10, Rev.6:9, al.;
    τ. Κυρίου, Act.8:25, 1Th.1:8, al.; τ. Χριστοῦ, Col.3:16, Rev.3:8;
    with genitive appos., Act.15:7; with genitive attrib., Heb.5:13.
    __5. a story, tale, narrative: Mat.28:15, Jhn.21:23, Act.1:1
    11:22; before περί, Luk.5:15. __6. That which is spoken of (Plat.,
    al.; V. Kennedy, Sources, 124), matter, affair, thing: Mat.21:24,
    Mrk.1:45 11:29, Luk.20:3, Act.8:21; of a matter in dispute, as a
    case or suit at law, Act.19:38; pl. (1Ma.7:33, al.), Luk.1:4.
    __II. Of the inward thought itself, Lat. ratio. __1. reason, __(a)
    of the mental faculty (Hdt., Plat., al.): κατὰ λόγον, Act.18:14;
    __(b) a reason, cause: τίνι λόγῳ, Act.10:29; παρεκτὸς λόγου
    πορνείας, Mat.5:32 19:9, WH, mg., R, mg. __2. account, __(a)
    regard: Act.20:24, Rec.; __(b) reckoning: Php.4:15, 17; συναίρειν
    (which see) λ., Mat.18:23 25:19; in forensic sense, Rom.14:12,
    Heb.13:17, 1Pe.4:5; with genitive of thing(s), Luk.16:2; before
    περί, Mat.12:36, Act.19:40, 1Pe.3:15. __3. proportion, analogy:
    Php.2:16 (Field, Notes, 193 f.). __III. ὁ λ., the Divine Word or
    Logos: Jhn.1:1, 14; τ. ζωῆς, 1Jn.1:1; τ. θεοῦ, Rev.19:13 (see
    Westc, Swete, CGT, in ll.; reff. in Artt., Logos, DB, DCG). (AS)

  Frequency                                  332 occurrences
  ----------------------------------------------------------------------
    Matthew                   33  ( 9.9%)  ████
    Mark                      24  ( 7.2%)  ███
    Luke                      32  ( 9.6%)  ████
    John                      40  (12.0%)  ██████
    Acts                      65  (19.6%)  █████████
    Romans                     8  ( 2.4%)  █
    1 Corinthians             17  ( 5.1%)  ██
    2 Corinthians              9  ( 2.7%)  █
    Galatians                  2  ( 0.6%)
    Ephesians                  4  ( 1.2%)
    Philippians                4  ( 1.2%)
    Colossians                 7  ( 2.1%)  █
    … and 12 more books

  Morphological Distribution
  ----------------------------------------------------------------------
    Accusative                            153  (46.1%)  ███████████████████████
    Nominative                             79  (23.8%)  ███████████
    Dative                                 60  (18.1%)  █████████
    Genitive                               37  (11.1%)  █████

  Top Collocates  (window ±5, corpus NT)
  ----------------------------------------------------------------------
    Lemma                  Gloss                       Obs        G²
    --------------------- ------------------------ -----  --------
    ὁ                      the/this/who                638     351.3
    ἀκούω                  to hear                      44      67.6
    τηρέω                  to keep: observe             15      41.8
    οὗτος                  this/he/she/it               68      32.6
    σπείρω                 to sow                       11      31.2
    διά                    through/because of           40      28.1
    θεός                   God                          62      27.0
    συντέμνω               to cut short                  3      25.0
    ἐν                     in/on/among                 100      19.6
    λαλέω                  to speak                     21      19.5

  Example Verses
  ----------------------------------------------------------------------
    [Mat 5:32]  λόγου
      But I say unto you, That whosoever shall put away his wife, saving for the cause of f...
    [Mat 5:37]  λόγος
      But let your communication be, Yea, yea; Nay, nay: for whatsoever is more than these ...
    [Mat 7:24]  λόγους
      Therefore whosoever heareth these sayings of mine, and doeth them, I will liken him u...
    [Mat 7:26]  λόγους
      And every one that heareth these sayings of mine, and doeth them not, shall be likene...

In [4]:
# Save a full Markdown report + distribution chart PNG
from bible_grammar.semantic_profile import save_semantic_profile

save_semantic_profile('H7307', output_dir='../../../output/reports/ot/lexicon')  # רוּחַ spirit/wind
save_semantic_profile('H1285', output_dir='../../../output/reports/ot/lexicon')  # בְּרִית covenant

  Saved: ../output/reports/h7307-semantic-profile.md
  Chart: ../output/reports/h7307-distribution.png

  Saved: ../output/reports/h1285-semantic-profile.md
  Chart: ../output/reports/h1285-distribution.png

'../output/reports/h1285-semantic-profile.md'

---
## 2. Synonym Comparison

Compare two or more near-synonym roots side by side: frequency, LXX equivalents
(shared renderings marked †), OT→LXX→NT trajectory, book distribution, and
morphological forms.

**Examples:** Love words (אָהֵב vs חָשַׁק) and Peace/Wholeness (שָׁלוֹם vs שָׁלֵם)

In [5]:
from bible_grammar.synonym import print_synonym_comparison

# Hebrew love words: אָהֵב (H157) vs חָשַׁק (H2836)
print_synonym_comparison(['H157', 'H2836'])

══════════════════════════════════════════════════════════════════════
  Synonym Comparison  (2 terms)
══════════════════════════════════════════════════════════════════════

  ┌─ H157  [Hebrew]
  │  Lemma      : אָהֵב
  │  Translit   : a.hav
  │  Gloss      : to love: lover
  │  Occurrences: 211
  └──────────────────────────────────────────────────

  ┌─ H2836  [Hebrew]
  │  Lemma      : חָשַׁק
  │  Translit   : cha.shaq
  │  Gloss      : to desire
  │  Occurrences: 11
  └──────────────────────────────────────────────────

  ──────────────────────────────────────────────────────────────────────
  FREQUENCY COMPARISON
  ──────────────────────────────────────────────────────────────────────
  H157 אָהֵב               211  ██████████████████████████████
  H2836 חָשַׁק              11  █

  ──────────────────────────────────────────────────────────────────────
  LXX TRANSLATION EQUIVALENTS  (word-level alignment)
  ──────────────────────────────────────────────────────────────────────
  H157 אָהֵב: ἀγαπάω 100%
  H2836 חָשַׁק: προαιρέω 100%

  ──────────────────────────────────────────────────────────────────────
  OT → LXX → NT TRAJECTORY
  ──────────────────────────────────────────────────────────────────────
  H157 אָהֵב → ἀγαπάω (G25)  NT: 11,521 occurrences
  H2836 חָשַׁק → προαιρέω (G4255)  NT: 1 occurrences

  ──────────────────────────────────────────────────────────────────────
  DISTRIBUTION  (top 5 books each)
  ──────────────────────────────────────────────────────────────────────

  H157 אָהֵב:
    Genesis                14  (  6.6%)  ███
    Exodus                  2  (  0.9%)
    Leviticus               2  (  0.9%)
    Deuteronomy            22  ( 10.4%)  █████
    Joshua                  2  (  0.9%)

  H2836 חָשַׁק:
    Genesis                 1  (  9.1%)  ████
    Exodus                  3  ( 27.3%)  █████████████
    Deuteronomy             3  ( 27.3%)  █████████████
    1 Kings                 1  (  9.1%)  ████
    2 Chronicles            1  (  9.1%)  ████

  ──────────────────────────────────────────────────────────────────────
  MORPHOLOGICAL FORMS  (top 5 each)
  ──────────────────────────────────────────────────────────────────────

  H157 אָהֵב:
stem          conjugation part_of_speech state  count  pct
                                  Suffix           71 33.6
 Qal              Perfect           Verb           46 21.8
 Qal           Participle           Verb           42 19.9
 Qal Infinitive construct           Verb           16  7.6
 Qal  Consecutive Perfect           Verb           11  5.2

  H2836 חָשַׁק:
stem           conjugation part_of_speech state  count  pct
 Qal               Perfect           Verb            7 63.6
Pual    Participle passive           Verb            2 18.2
Piel Consecutive Imperfect           Verb            1  9.1
 Qal Consecutive Imperfect           Verb            1  9.1

In [6]:
# NT love words: ἀγάπη (G26) vs φιλέω (G5368)
print_synonym_comparison(['G26', 'G5368'])

══════════════════════════════════════════════════════════════════════
  Synonym Comparison  (2 terms)
══════════════════════════════════════════════════════════════════════

  ┌─ G26  [Greek]
  │  Lemma      : ἀγάπη
  │  Translit   : agapē
  │  Gloss      : love
  │  Occurrences: 114
  └──────────────────────────────────────────────────

  ┌─ G5368  [Greek]
  │  Lemma      : φιλέω
  │  Translit   : phileō
  │  Gloss      : to love
  │  Occurrences: 25
  └──────────────────────────────────────────────────

  ──────────────────────────────────────────────────────────────────────
  FREQUENCY COMPARISON
  ──────────────────────────────────────────────────────────────────────
  G26 ἀγάπη                114  ██████████████████████████████
  G5368 φιλέω               25  ██████

  ──────────────────────────────────────────────────────────────────────
  DISTRIBUTION  (top 5 books each)
  ──────────────────────────────────────────────────────────────────────

  G26 ἀγάπη:
    Matthew                 1  (  0.9%)
    Luke                    1  (  0.9%)
    John                    7  (  6.1%)  ███
    Romans                  9  (  7.9%)  ███
    1 Corinthians          14  ( 12.3%)  ██████

  G5368 φιλέω:
    Matthew                 5  ( 20.0%)  ██████████
    Mark                    1  (  4.0%)  ██
    Luke                    2  (  8.0%)  ████
    John                   13  ( 52.0%)  █████████████████████████
    1 Corinthians           1  (  4.0%)  ██

  ──────────────────────────────────────────────────────────────────────
  MORPHOLOGICAL FORMS  (top 1 each)
  ──────────────────────────────────────────────────────────────────────

  G26 ἀγάπη:
tense voice mood part_of_speech  count   pct
                           Noun    114 100.0

  G5368 φιλέω:
    tense  voice        mood part_of_speech  count  pct
  Present Active  Indicative           Verb     11 44.0
  Present Active  Participle           Verb      6 24.0
Imperfect Active  Indicative           Verb      3 12.0
   Aorist Active Subjunctive           Verb      2  8.0
   Aorist Active  Infinitive           Verb      1  4.0

In [7]:
# Return a compact DataFrame for notebook display
from bible_grammar.synonym import synonym_table

synonym_table(['H7307', 'H5397'])  # רוּחַ spirit vs נְשָׁמָה breath

  strongs     lemma   gloss  total_occurrences lxx_primary  lxx_primary_pct  nt_occurrences
0   H7307     רוּחַ  spirit                378      πνεῦμα             87.0             606
1   H5397  נִשְׁמָא  breath                 24        πνοή            100.0               2

---
## 3. LXX Translation Consistency

Measures how uniformly each LXX book/translator renders a given Hebrew root.
High consistency (>90%) = one dominant Greek equivalent.
Low consistency or divergent books may indicate semantic range, different translation
philosophy, or recensional differences.

**Example:** רוּחַ (H7307) splits between πνεῦμα (*spirit*) and ἄνεμος (*wind*)

In [8]:
from bible_grammar.lxx_consistency import print_lxx_consistency

print_lxx_consistency('H7307')  # רוּחַ spirit/wind

══════════════════════════════════════════════════════════════════════
  LXX Translation Consistency: H7307
  Hebrew: רוּחַ  (spirit)
══════════════════════════════════════════════════════════════════════

  Total aligned tokens : 223
  Corpus-wide primary  : πνεῦμα  (87%)
  Overall consistency  : 88%
  Divergent books      : Pro, Jer, Dan

  Book                 Tokens  Primary rendering    Pct  Alt renderings
  ------------------- ------  ----------------- -----  ------------------------------
  Genesis                   7  πνεῦμα               100%  ██████████
  Exodus                    8  πνεῦμα                62%  ██████  ἄνεμος×3
  Numbers                  12  πνεῦμα               100%  ██████████
  Judges                    9  πνεῦμα               100%  ██████████
  1 Samuel                 12  πνεῦμα               100%  ██████████
  2 Samuel                  3  πνεῦμα                67%  ██████  ἄνεμος×1
  1 Kings                   7  πνεῦμα               100%  ██████████
  2 Kings                   5  πνεῦμα               100%  ██████████
  2 Chronicles              8  πνεῦμα               100%  ██████████
  Job                      20  πνεῦμα                85%  ████████  ἄνεμος×3
  Proverbs                  3  ἄνεμος                67%  ██████  πνεῦμα×1 ←
  Ecclesiastes             17  πνεῦμα                94%  █████████  ἄνεμος×1
  Isaiah                   35  πνεῦμα                91%  █████████  ἄνεμος×3
  Jeremiah                  8  ἄνεμος                62%  ██████  πνεῦμα×3 ←
  Ezekiel                  34  πνεῦμα                82%  ████████  ἄνεμος×6
  Daniel                    3  ἄνεμος                67%  ██████  πνεῦμα×1 ←
  Hosea                     4  πνεῦμα                75%  ███████  ἄνεμος×1
  Zechariah                 7  πνεῦμα                86%  ████████  ἄνεμος×1

  ← primary rendering differs from corpus-wide primary (πνεῦμα)

In [9]:
print_lxx_consistency('H1697')  # דָּבָר word — most divergent theological term

══════════════════════════════════════════════════════════════════════
  LXX Translation Consistency: H1697
  Hebrew: דָּבָר  (word)
══════════════════════════════════════════════════════════════════════

  Total aligned tokens : 735
  Corpus-wide primary  : λόγος  (64%)
  Overall consistency  : 78%
  Divergent books      : Gen, Exo, Lev, Num, Deu, Jos, 1Sa, Ezr, Job

  Book                 Tokens  Primary rendering    Pct  Alt renderings
  ------------------- ------  ----------------- -----  ------------------------------
  Genesis                  38  ῥῆμα                  95%  █████████  λόγος×2 ←
  Exodus                   35  ῥῆμα                  69%  ██████  λόγος×11 ←
  Leviticus                 6  ῥῆμα                  83%  ████████  λόγος×1 ←
  Numbers                  19  ῥῆμα                  84%  ████████  λόγος×3 ←
  Deuteronomy              51  ῥῆμα                  55%  █████  λόγος×23 ←
  Joshua                   16  ῥῆμα                  69%  ██████  λόγος×5 ←
  Judges                   22  λόγος                 59%  █████  ῥῆμα×9
  1 Samuel                 45  ῥῆμα                  71%  ███████  λόγος×13 ←
  2 Samuel                 46  λόγος                 52%  █████  ῥῆμα×22
  1 Kings                  50  λόγος                 54%  █████  ῥῆμα×23
  2 Kings                  52  λόγος                 64%  ██████  ῥῆμα×19
  1 Chronicles             17  λόγος                 94%  █████████  ῥῆμα×1
  2 Chronicles             40  λόγος                 95%  █████████  ῥῆμα×2
  Ezra                     10  ῥῆμα                  60%  ██████  λόγος×4 ←
  Esther                   10  λόγος                 80%  ████████  λοιπός×1  ῥῆμα×1
  Job                      13  ῥῆμα                  69%  ██████  λόγος×4 ←
  Proverbs                 15  λόγος                100%  ██████████
  Ecclesiastes             17  λόγος                 82%  ████████  ῥῆμα×3
  Isaiah                   37  λόγος                 81%  ████████  ῥῆμα×7
  Jeremiah                 77  λόγος                 95%  █████████  ῥῆμα×4
  Ezekiel                  67  λόγος                 98%  █████████  ῥῆμα×1
  Hosea                     3  λόγος                 67%  ██████  ῥῆμα×1
  Amos                      8  λόγος                100%  ██████████
  Jonah                     3  λόγος                100%  ██████████
  Micah                     3  λόγος                100%  ██████████
  Haggai                    5  λόγος                100%  ██████████
  Zechariah                19  λόγος                100%  ██████████
  Malachi                   3  λόγος                100%  ██████████

  ← primary rendering differs from corpus-wide primary (λόγος)

In [10]:
# Heatmap: rows=LXX lemmas, cols=OT books, cells=% usage
from bible_grammar.lxx_consistency import consistency_heatmap

consistency_heatmap('H7307', output_path='../../../output/charts/ot/lexicon/ruach-consistency.png')

  Saved: ../output/charts/ruach-consistency.png

In [11]:
# Batch summary across multiple theological roots
from bible_grammar.lxx_consistency import batch_consistency

roots = ['H1285', 'H2617', 'H7965', 'H6944', 'H7307', 'H1697', 'H4941', 'H6664']
df = batch_consistency(roots)
df

,strongs,lemma,gloss,total_aligned,corpus_primary,corpus_primary_pct,overall_consistency,n_divergent_books
0,H1285,בְּרִית,covenant,198,διαθήκη,100.0,100.0,0
1,H2617,חֶ֫סֶד,kindness,74,ἔλεος,100.0,100.0,0
2,H7965,שָׁלוֹם,peace,116,εἰρήνη,100.0,100.0,0
3,H6944,קֹ֫דֶשׁ,holiness,253,ἅγιος,100.0,100.0,0
4,H7307,רוּחַ,spirit,223,πνεῦμα,87.0,88.1,3
5,H1697,דָּבָר,word,735,λόγος,64.2,78.0,9
7,H6664,צֶ֫דֶק,righteousness,46,δικαιοσύνη,60.9,75.7,2
6,H4941,מִשְׁפָּט,justice: judgement,213,κρίμα,53.1,73.7,8

---
## 4. NT Quotation Word Alignment

For each NT quotation of the OT, analyses whether the NT author's Greek vocabulary
follows the LXX wording or diverges toward the Hebrew MT.

**Verdict key:**
- `LXX` — NT word's Strong's number appears in the LXX rendering
- `LXX+MT` — matches LXX and the Hebrew root is also in the OT verse
- `MT-diverge` — NT word's Hebrew root is in the OT verse but LXX used different Greek
- `neutral` — function word or no alignment data

In [12]:
from bible_grammar.quotation_align import print_quotation_align

# Matthew 4:4 — "Man shall not live by bread alone" (Deut 8:3)
print_quotation_align('Mat', 4, 4)

══════════════════════════════════════════════════════════════════════
  NT Quotation Alignment: Mat 4:4
  "But he answered and said, It is written, Man shall not live by bread alone, but by every w..."
══════════════════════════════════════════════════════════════════════

  ┌─ OT source: Deu 8:3  (confidence votes: 349)
  │  Text alignment: FOLLOWS LXX  (75% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  ἀποκριθεὶς             G611      ·
  εἶπεν·                 G2036     ·
  γέγραπται·             G1125     ·
  ἄρτῳ                   G740      ✓ LXX+MT     H3899H     הַ/לֶּ֤חֶם
  μόνῳ                   G3441     ✓ LXX        H0905H     לְ/בַדּ/וֹ֙
  ζήσεται                G2198     ✓ LXX+MT     H2421      יִחְיֶ֣ה
  ἄνθρωπος,              G444      ✓ LXX        H0120G     הָֽ/אָדָ֔ם
  παντὶ                  G3956     ✓ LXX+MT     H3605      כָּל\־
  ῥήματι                 G4487     ✓ LXX
  ἐκπορευομένῳ           G1607     ✓ LXX
  στόματος               G4750     ✓ LXX+MT     H6310G     פִֽי\־
  θεοῦ.¶                 G2316     ✓ LXX

  OT (Deu 8:3): "And he humbled thee, and suffered thee to hunger, and fed thee with manna, which thou knewest n..."

  ┌─ OT source: Exo 16:15  (confidence votes: 33)
  │  Text alignment: MT-LEANING  (17% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  ἀποκριθεὶς             G611      ·
  εἶπεν·                 G2036     ✓ LXX        H0559      וַ/יֹּ֨אמְר֜וּ
  γέγραπται·             G1125     ·
  ἄρτῳ                   G740      ✓ LXX+MT     H3899H     הַ/לֶּ֔חֶם
  μόνῳ                   G3441     ·
  ζήσεται                G2198     ·
  ἄνθρωπος,              G444      ·
  παντὶ                  G3956     ·
  ῥήματι                 G4487     ·
  ἐκπορευομένῳ           G1607     ·
  στόματος               G4750     ·
  θεοῦ.¶                 G2316     ·

  OT (Exo 16:15): "And when the children of Israel saw it, they said one to another, It is manna: for they wist no..."

  ┌─ OT source: Exo 16:35  (confidence votes: 27)
  │  Text alignment: MT-LEANING  (0% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  ἀποκριθεὶς             G611      ·
  εἶπεν·                 G2036     ·
  γέγραπται·             G1125     ·
  ἄρτῳ                   G740      ·
  μόνῳ                   G3441     ·
  ζήσεται                G2198     ·
  ἄνθρωπος,              G444      ·
  παντὶ                  G3956     ·
  ῥήματι                 G4487     ·
  ἐκπορευομένῳ           G1607     ·
  στόματος               G4750     ·
  θεοῦ.¶                 G2316     ·

  OT (Exo 16:35): "And the children of Israel did eat manna forty years, until they came to a land inhabited; they..."

  ┌─ OT source: Exo 16:8  (confidence votes: 20)
  │  Text alignment: MT-LEANING  (25% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  ἀποκριθεὶς             G611      ·
  εἶπεν·                 G2036     ✓ LXX        H0559      וַ/יֹּ֣אמֶר
  γέγραπται·             G1125     ·
  ἄρτῳ                   G740      ✓ LXX+MT     H3899H     וְ/לֶ֤חֶם
  μόνῳ                   G3441     ·
  ζήσεται                G2198     ·
  ἄνθρωπος,              G444      ·
  παντὶ                  G3956     ·
  ῥήματι                 G4487     ·
  ἐκπορευομένῳ           G1607     ·
  στόματος               G4750     ·
  θεοῦ.¶                 G2316     ✓ LXX

  OT (Exo 16:8): "And Moses said, This shall be, when the Lord shall give you in the evening flesh to eat, and in..."

  ┌─ OT source: 2Ki 7:1  (confidence votes: 15)
  │  Text alignment: MT-LEANING  (8% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  ἀποκριθεὶς             G611      ·
  εἶπεν·                 G2036     ✓ LXX        H0559      וַ/יֹּ֣אמֶר
  γέγραπται·             G1125     ·
  ἄρτῳ                   G740      ·
  μόνῳ                   G3441     ·
  ζήσεται                G2198     ·
  ἄνθρωπος,              G444      ·
  παντὶ                  G3956     ·
  ῥήματι                 G4487     ·
  ἐκπορευομένῳ           G1607     ·
  στόματος               G4750     ·
  θεοῦ.¶                 G2316     ·

  ┌─ OT source: Mal 3:9  (confidence votes: 12)
  │  Text alignment: MT-LEANING  (0% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  ἀποκριθεὶς             G611      ·
  εἶπεν·                 G2036     ·
  γέγραπται·             G1125     ·
  ἄρτῳ                   G740      ·
  μόνῳ                   G3441     ·
  ζήσεται                G2198     ·
  ἄνθρωπος,              G444      ·
  παντὶ                  G3956     ·
  ῥήματι                 G4487     ·
  ἐκπορευομένῳ           G1607     ·
  στόματος               G4750     ·
  θεοῦ.¶                 G2316     ·

  OT (Mal 3:9): "Ye are cursed with a curse: for ye have robbed me, even this whole nation."

  ┌─ OT source: Exo 23:15  (confidence votes: 11)
  │  Text alignment: MT-LEANING  (0% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  ἀποκριθεὶς             G611      ·
  εἶπεν·                 G2036     ·
  γέγραπται·             G1125     ·
  ἄρτῳ                   G740      ·
  μόνῳ                   G3441     ·
  ζήσεται                G2198     ·
  ἄνθρωπος,              G444      ·
  παντὶ                  G3956     ·
  ῥήματι                 G4487     ·
  ἐκπορευομένῳ           G1607     ·
  στόματος               G4750     ·
  θεοῦ.¶                 G2316     ·

  OT (Exo 23:15): "Thou shalt keep the feast of unleavened bread: (thou shalt eat unleavened bread seven days, as ..."

  ┌─ OT source: 1Ki 17:12  (confidence votes: 11)
  │  Text alignment: MT-LEANING  (25% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  ἀποκριθεὶς             G611      ·
  εἶπεν·                 G2036     ✓ LXX        H0559      וַ/תֹּ֗אמֶר
  γέγραπται·             G1125     ·
  ἄρτῳ                   G740      ·
  μόνῳ                   G3441     ·
  ζήσεται                G2198     ✓ LXX+MT     H2416A     חַי\־
  ἄνθρωπος,              G444      ·
  παντὶ                  G3956     ·
  ῥήματι                 G4487     ·
  ἐκπορευομένῳ           G1607     ·
  στόματος               G4750     ·
  θεοῦ.¶                 G2316     ✓ LXX        H0430G     אֱלֹהֶ֙י/ךָ֙

  ┌─ OT source: Hag 2:16  (confidence votes: 10)
  │  Text alignment: MT-LEANING  (0% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  ἀποκριθεὶς             G611      ·
  εἶπεν·                 G2036     ·
  γέγραπται·             G1125     ·
  ἄρτῳ                   G740      ·
  μόνῳ                   G3441     ·
  ζήσεται                G2198     ·
  ἄνθρωπος,              G444      ·
  παντὶ                  G3956     ·
  ῥήματι                 G4487     ·
  ἐκπορευομένῳ           G1607     ·
  στόματος               G4750     ·
  θεοῦ.¶                 G2316     ·

  OT (Hag 2:16): "Since those days were, when one came to an heap of twenty measures, there were but ten: when on..."

  ┌─ OT source: 2Ki 4:42  (confidence votes: 9)
  │  Text alignment: MT-LEANING  (33% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  ἀποκριθεὶς             G611      ·
  εἶπεν·                 G2036     ✓ LXX        H0559      וַ/יֹּ֕אמֶר
  γέγραπται·             G1125     ·
  ἄρτῳ                   G740      ✓ LXX+MT     H3899H     לֶ֤חֶם
  μόνῳ                   G3441     ·
  ζήσεται                G2198     ·
  ἄνθρωπος,              G444      ✓ LXX
  παντὶ                  G3956     ·
  ῥήματι                 G4487     ·
  ἐκπορευομένῳ           G1607     ·
  στόματος               G4750     ·
  θεοῦ.¶                 G2316     ✓ LXX        H0430G     הָ/אֱלֹהִ֜ים

In [13]:
# Hebrews 1:5 — "Thou art my Son" (Psalm 2:7) — one of Hebrews' clearest LXX alignments
print_quotation_align('Heb', 1, 5)

══════════════════════════════════════════════════════════════════════
  NT Quotation Alignment: Heb 1:5
  "For unto which of the angels said he at any time, Thou art my Son, this day have I begotte..."
══════════════════════════════════════════════════════════════════════

  ┌─ OT source: Psa 2:7  (confidence votes: 61)
  │  Text alignment: FOLLOWS LXX  (74% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  εἶπέν                  G2036     ✓ LXX        H0559      אָמַ֘ר
  ἀγγέλων·               G32       ·
  υἱός                   G5207     ✓ LXX+MT     H1121A     בְּנִ֥/י
  μου                    G3165     ✓ LXX
  εἶ                     G1510     ✓ LXX
  σύ,                    G4771     ✓ LXX        H0859A     אַ֑תָּה
  ἐγὼ                    G1473     ✓ LXX        H0589      אֲ֝נִ֗י
  σήμερον                G4594     ✓ LXX
  γεγέννηκά              G1080     ✓ LXX+MT     H3205      יְלִדְתִּֽי/ךָ\׃
  σε;                    G4771     ✓ LXX        H0859A     אַ֑תָּה
  πάλιν·                 G3825     ·
  ἐγὼ                    G1473     ✓ LXX        H0589      אֲ֝נִ֗י
  ἔσομαι                 G1510     ✓ LXX
  αὐτῷ                   G846      ·
  πατέρα,                G3962     ·
  αὐτὸς                  G846      ·
  ἔσται                  G1510     ✓ LXX
  μοι                    G3165     ✓ LXX
  υἱόν;                  G5207     ✓ LXX+MT     H1121A     בְּנִ֥/י

  OT (Psa 2:7): "I will declare the decree: the Lord hath said unto me, Thou art my Son; this day have I begotte..."

  ┌─ OT source: 2Sa 7:14  (confidence votes: 19)
  │  Text alignment: MIXED  (53% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  εἶπέν                  G2036     ·
  ἀγγέλων·               G32       ·
  υἱός                   G5207     ✓ LXX+MT     H1121A     לְ/בֵ֑ן
  μου                    G3165     ·
  εἶ                     G1510     ✓ LXX+MT     H1961      אֶהְיֶה\־
  σύ,                    G4771     ·
  ἐγὼ                    G1473     ✓ LXX        H0589      אֲנִי֙
  σήμερον                G4594     ·
  γεγέννηκά              G1080     ·
  σε;                    G4771     ·
  πάλιν·                 G3825     ·
  ἐγὼ                    G1473     ✓ LXX        H0589      אֲנִי֙
  ἔσομαι                 G1510     ✓ LXX+MT     H1961      אֶהְיֶה\־
  αὐτῷ                   G846      ✓ LXX        H9033      לּ֣/וֹ
  πατέρα,                G3962     ✓ LXX        H0001G     לְ/אָ֔ב
  αὐτὸς                  G846      ✓ LXX        H9033      לּ֣/וֹ
  ἔσται                  G1510     ✓ LXX+MT     H1961      אֶהְיֶה\־
  μοι                    G3165     ·
  υἱόν;                  G5207     ✓ LXX+MT     H1121A     לְ/בֵ֑ן

  ┌─ OT source: 1Ch 17:13  (confidence votes: 17)
  │  Text alignment: MIXED  (53% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  εἶπέν                  G2036     ·
  ἀγγέλων·               G32       ·
  υἱός                   G5207     ✓ LXX+MT     H1121A     לְ/בֵ֑ן
  μου                    G3165     ·
  εἶ                     G1510     ✓ LXX+MT     H1961      אֶֽהְיֶה\־
  σύ,                    G4771     ·
  ἐγὼ                    G1473     ✓ LXX        H0589      אֲנִי֙
  σήμερον                G4594     ·
  γεγέννηκά              G1080     ·
  σε;                    G4771     ·
  πάλιν·                 G3825     ·
  ἐγὼ                    G1473     ✓ LXX        H0589      אֲנִי֙
  ἔσομαι                 G1510     ✓ LXX+MT     H1961      אֶֽהְיֶה\־
  αὐτῷ                   G846      ✓ LXX        H9033      לּ֣/וֹ
  πατέρα,                G3962     ✓ LXX        H0001G     לְ/אָ֔ב
  αὐτὸς                  G846      ✓ LXX        H9033      לּ֣/וֹ
  ἔσται                  G1510     ✓ LXX+MT     H1961      אֶֽהְיֶה\־
  μοι                    G3165     ·
  υἱόν;                  G5207     ✓ LXX+MT     H1121A     לְ/בֵ֑ן

  ┌─ OT source: 1Ch 22:10  (confidence votes: 16)
  │  Text alignment: MIXED  (42% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  εἶπέν                  G2036     ·
  ἀγγέλων·               G32       ·
  υἱός                   G5207     ✓ LXX+MT     H1121A     לְ/בֵ֔ן
  μου                    G3165     ·
  εἶ                     G1510     ✓ LXX+MT     H1961      יִהְיֶה\־
  σύ,                    G4771     ·
  ἐγὼ                    G1473     ·
  σήμερον                G4594     ·
  γεγέννηκά              G1080     ·
  σε;                    G4771     ·
  πάλιν·                 G3825     ·
  ἐγὼ                    G1473     ·
  ἔσομαι                 G1510     ✓ LXX+MT     H1961      יִהְיֶה\־
  αὐτῷ                   G846      ✓ LXX        H9033      ל֖/וֹ
  πατέρα,                G3962     ✓ LXX        H0001G     לְ/אָ֑ב
  αὐτὸς                  G846      ✓ LXX        H9033      ל֖/וֹ
  ἔσται                  G1510     ✓ LXX+MT     H1961      יִהְיֶה\־
  μοι                    G3165     ·
  υἱόν;                  G5207     ✓ LXX+MT     H1121A     לְ/בֵ֔ן

  ┌─ OT source: Psa 89:26  (confidence votes: 15)
  │  Text alignment: MT-LEANING  (0% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  εἶπέν                  G2036     ·
  ἀγγέλων·               G32       ·
  υἱός                   G5207     ·
  μου                    G3165     ·
  εἶ                     G1510     ·
  σύ,                    G4771     ·
  ἐγὼ                    G1473     ·
  σήμερον                G4594     ·
  γεγέννηκά              G1080     ·
  σε;                    G4771     ·
  πάλιν·                 G3825     ·
  ἐγὼ                    G1473     ·
  ἔσομαι                 G1510     ·
  αὐτῷ                   G846      ·
  πατέρα,                G3962     ·
  αὐτὸς                  G846      ·
  ἔσται                  G1510     ·
  μοι                    G3165     ·
  υἱόν;                  G5207     ·

  OT (Psa 89:26): "He shall cry unto me, Thou art my father, my God, and the rock of my salvation."

  ┌─ OT source: 1Ch 28:6  (confidence votes: 7)
  │  Text alignment: MIXED  (47% follows LXX)
  └────────────────────────────────────────────────────────────

  NT word                Strongs   Verdict      Hebrew root Hebrew word
  --------------------- -------- ----------- --------- --------------------
  εἶπέν                  G2036     ✓ LXX        H0559      וַ/יֹּ֣אמֶר
  ἀγγέλων·               G32       ·
  υἱός                   G5207     ✓ LXX+MT     H1121A     בִנְ/ךָ֔
  μου                    G3165     ·
  εἶ                     G1510     ✓ LXX+MT     H1961      אֶֽהְיֶה\־
  σύ,                    G4771     ·
  ἐγὼ                    G1473     ·
  σήμερον                G4594     ·
  γεγέννηκά              G1080     ·
  σε;                    G4771     ·
  πάλιν·                 G3825     ·
  ἐγὼ                    G1473     ·
  ἔσομαι                 G1510     ✓ LXX+MT     H1961      אֶֽהְיֶה\־
  αὐτῷ                   G846      ✓ LXX        H9033      ב֥/וֹ
  πατέρα,                G3962     ✓ LXX        H0001G     לְ/אָֽב\׃
  αὐτὸς                  G846      ✓ LXX        H9033      ב֥/וֹ
  ἔσται                  G1510     ✓ LXX+MT     H1961      אֶֽהְיֶה\־
  μοι                    G3165     ·
  υἱόν;                  G5207     ✓ LXX+MT     H1121A     בִנְ/ךָ֔

In [14]:
# Batch: all high-confidence quotations in Romans
from bible_grammar.quotation_align import batch_align

df = batch_align(nt_book='Rom', min_votes=40)
df

       nt_ref     ot_ref  votes  lxx_following_pct  mt_diverge_count  total_content_words     summary
0    Rom 8:29    Jer 1:5   1143                0.0                 0                   11  MT-leaning
1    Rom 8:28  Gen 50:20    320               30.0                 0                   10  MT-leaning
2    Rom 8:31  Psa 118:6    264               50.0                 0                    4       mixed
3    Rom 3:23   Ecc 7:20    220               20.0                 0                    5  MT-leaning
4    Rom 12:2  Ezk 36:26    213                0.0                 0                   13  MT-leaning
..        ...        ...    ...                ...               ...                  ...         ...
75   Rom 1:20  Isa 40:26     41               28.6                 0                   14  MT-leaning
76   Rom 8:31  Psa 46:11     41                0.0                 0                    4  MT-leaning
77   Rom 3:10   Psa 14:1     41                0.0                 0                    4  MT-leaning
78  Rom 12:19  Pro 24:29     40                0.0                 0                   12  MT-leaning
79  Rom 12:19  Pro 20:22     40                0.0                 0                   12  MT-leaning

[80 rows x 7 columns]

In [15]:
# Summary statistics: what % of NT quotations follow the LXX vs lean toward MT?
df_all = batch_align(min_votes=50)
print(df_all['summary'].value_counts())
print()
print('Mean LXX-following %:', df_all['lxx_following_pct'].mean().round(1))

summary
MT-leaning     426
mixed           38
follows LXX     17
Name: count, dtype: int64

Mean LXX-following %: 15.3

---
## 5. Theological Term Map

Traces key theological concepts across OT Hebrew → LXX Greek → NT Greek,
showing whether NT authors adopt LXX vocabulary or use fresh terminology.

The built-in `THEOLOGICAL_TERMS` dict groups roots by theological domain.

In [16]:
from bible_grammar.termmap import print_term_map, THEOLOGICAL_TERMS

# Show available domains
for domain, roots in THEOLOGICAL_TERMS.items():
    print(f"  {domain:<35} {roots}")

  Covenant / Faithfulness             ['H1285', 'H2617', 'H530', 'H571']
  Holiness / Purity                   ['H6944', 'H6918', 'H2891', 'H2930']
  Righteousness / Justice             ['H6664', 'H4941', 'H3477']
  Salvation / Redemption              ['H3467', 'H1350', 'H6299', 'H3444']
  Glory / Honour                      ['H3519', 'H1935']
  Word / Speech                       ['H1697', 'H565', 'H6310']
  Spirit / Breath / Wind              ['H7307']
  Knowledge / Wisdom                  ['H3045', 'H2451', 'H998']
  Love                                ['H157', 'H160']
  Peace                               ['H7965']
  Fear / Awe                          ['H3372', 'H3374']
  Repentance / Return                 ['H7725', 'H5162']
  Praise / Worship                    ['H1984', 'H7812', 'H3034']
  Creation / Making                   ['H1254', 'H6213']
  Sin / Transgression                 ['H2398', 'H6588', 'H5771']
  Atonement                           ['H3722']
  Blessing / Curse                    ['H1288', 'H423']
  Faith / Trust                       ['H539', 'H982']
  Wrath / Anger                       ['H639', 'H2534']
  Mercy / Compassion                  ['H7356', 'H2603']

In [17]:
print_term_map(theme='Covenant / Faithfulness')

──────────────────────────────────────────────────────────────────────
  Covenant / Faithfulness
──────────────────────────────────────────────────────────────────────
  Root       Lemma          Gloss                           OT  LXX equivalents (word-level alignment)
  --------- ------------- --------------------------- -----  --------------------------------------
  H1285      בְּרִית        covenant                       284  διαθήκη 100% [NT:33]
  H2617      חֶ֫סֶד         kindness                       247  ἔλεος 100% [NT:27]
  H530       אֱמוּנָה       faithfulness                   474  πίστις 100% [NT:242]
  H571       אֱמֶת          truth: faithful                291  ἀλήθεια 100% [NT:110]

In [18]:
print_term_map(theme='Salvation / Redemption')

──────────────────────────────────────────────────────────────────────
  Salvation / Redemption
──────────────────────────────────────────────────────────────────────
  Root       Lemma          Gloss                           OT  LXX equivalents (word-level alignment)
  --------- ------------- --------------------------- -----  --------------------------------------
  H3467      יָשַׁע         to save                        206  σώζω 100% [NT:109]
  H1350      גָּאַל         to redeem: redeem              104  λυτρόω 100% [NT:3]
  H6299      פָּדָה         to ransom                       59  λυτρόω 100% [NT:3]
  H3444      יְשׁוּעָה      salvation                       78  σωτηρία 100% [NT:51]

In [19]:
# Compact table form — pass the strongs list for a domain
from bible_grammar.termmap import term_map_table, THEOLOGICAL_TERMS

term_map_table(THEOLOGICAL_TERMS['Righteousness / Justice'])

  theme heb_strongs  heb_lemma           heb_gloss  ot_count   lxx_lemma lxx_strongs      lxx_gloss  lxx_pct  nt_count
0             H6664     צֶ֫דֶק       righteousness       119  δικαιοσύνη       G1343  righteousness     60.9        94
1             H6664     צֶ֫דֶק       righteousness       119     δίκαιος       G1342           just     39.1        81
2             H4941  מִשְׁפָּט  justice: judgement       422       κρίμα       G2917       judgment     53.1        28
3             H4941  מִשְׁפָּט  justice: judgement       422      κρίσις       G2920       judgment     46.9        48

---
## 6. Phrase & Proximity Search

Search for consecutive word sequences or statistically proximate words.
Tokens can be Strong's numbers, Hebrew/Greek lemmas, or `'*'` wildcards.
Proximity search supports cross-verse boundaries using a global position index.

In [20]:
from bible_grammar.phrase import phrase_search, print_phrase_results

# "The LORD said" — consecutive phrase in OT
results = phrase_search(['H3068', 'H559'], corpus='OT', max_results=15)
print_phrase_results(results)

  15 matches:

  [1Ch 17:16]  יְהוָ֑ה  וַ/יֹּ֗אמֶר
  [1Ch 21:18]  יְהוָ֛ה  אָמַ֥ר
  [1Ch 22:8]  יְהוָה֙  לֵ/אמֹ֔ר
  [1Ki 2:8]  בַֽ/יהוָה֙  לֵ/אמֹ֔ר
  [1Ki 2:23]  בַּֽ/יהוָ֖ה  לֵ/אמֹ֑ר
  [1Ki 2:30]  יְהוָ֗ה  וַ/יֹּ֨אמֶר
  [1Ki 8:12]  יְהוָ֣ה  אָמַ֔ר
  [1Ki 13:2]  יְהוָ֔ה  וַ/יֹּ֙אמֶר֙
  [1Ki 13:9]  יְהוָה֙  לֵ/אמֹ֔ר
  [1Ki 13:18]  יְהוָ֜ה  לֵ/אמֹ֗ר
  [1Ki 14:5]  וַ/יהוָ֞ה  אָמַ֣ר
  [1Ki 17:20]  יְהוָ֖ה  וַ/יֹּאמַ֑ר
  [1Ki 17:21]  יְהוָ֖ה  וַ/יֹּאמַ֑ר
  [1Ki 21:23]  יְהוָ֖ה  לֵ/אמֹ֑ר
  [1Ki 22:21]  יְהוָ֔ה  וַ/יֹּ֖אמֶר

In [21]:
# Phrase with wildcard: "spirit of the LORD" (רוּחַ + * + יְהוָה)
results = phrase_search(['H7307', '*', 'H3068'], corpus='OT', max_results=20)
print_phrase_results(results)

  4 matches:

  [Ezk 3:14]  רוּחִ֔/י  וְ/יַד\־  יְהוָ֥ה
    So the spirit lifted me up, and took me away, and I went in bitterness, in the heat of my spirit;...
  [Isa 54:6]  ר֖וּחַ  קְרָאָ֣/ךְ  יְהוָ֑ה
    For the Lord hath called thee as a woman forsaken and grieved in spirit, and a wife of youth, whe...
  [Psa 35:5]  ר֑וּחַ  וּ/מַלְאַ֖ךְ  יְהוָ֣ה
    Let them be as chaff before the wind: and let the angel of the Lord chase them.
  [Zec 4:6]  בְּ/רוּחִ֔/י  אָמַ֖ר  יְהוָ֥ה
    Then he answered and spake unto me, saying, This is the word of the Lord unto Zerubbabel, saying,...

In [22]:
from bible_grammar.phrase import proximity_search, print_proximity_results

# שָׁלוֹם near אֱמֶת (peace near truth/faithfulness) within 5 words
results = proximity_search(['H7965', 'H571'], within=5, corpus='OT', max_results=20)
print_proximity_results(results)

  9 matches:

  [2Ki 20:19]  שָׁל֥וֹם  …  וֶ/אֱמֶ֖ת  (dist: 1)
  [Est 9:30]  שָׁל֖וֹם  …  וֶ/אֱמֶֽת\׃  (dist: 1)
    And he sent the letters unto all the Jews, to the hundred twenty and seven provinces of the kingd...
  [Isa 39:8]  שָׁל֥וֹם  …  וֶ/אֱמֶ֖ת  (dist: 1)
    Then said Hezekiah to Isaiah, Good is the word of the Lord which thou hast spoken. He said moreov...
  [Jer 14:13]  שְׁל֤וֹם  …  אֱמֶת֙  (dist: 1)
    Then said I, Ah, Lord God! behold, the prophets say unto them, Ye shall not see the sword, neithe...
  [Jer 33:6]  שָׁל֖וֹם  …  וֶ/אֱמֶֽת\׃  (dist: 1)
    Behold, I will bring it health and cure, and I will cure them, and will reveal unto them the abun...
  [Zec 8:19]  וְ/הַ/שָּׁל֖וֹם  …  וְ/הָ/אֱמֶ֥ת  (dist: 1)
    Thus saith the Lord of hosts; The fast of the fourth month, and the fast of the fifth, and the fa...
  [Psa 85:10]  וְ/שָׁל֣וֹם (Psa 85:10)  …  אֱ֭מֶת (Psa 85:11)  (dist: 2)
    Mercy and truth are met together; righteousness and peace have kissed each other.
  [Zec 8:16]  שָׁל֔וֹם  …  אֱמֶת֙  (dist: 2)
    These are the things that ye shall do; Speak ye every man the truth to his neighbour; execute the...
  [Pro 3:2]  וְ֝/שָׁל֗וֹם (Pro 3:2)  …  וֶ/אֱמֶ֗ת (Pro 3:3)  (dist: 4)
    For length of days, and long life, and peace, shall they add to thee.

In [23]:
# NT: λόγος near θεός (word near God) within 8 words
results = proximity_search(['G3056', 'G2316'], within=8, corpus='NT', max_results=15)
print_proximity_results(results)

  15 matches:

  [Mat 15:6]  λόγον  …  θεοῦ  (dist: 2)
    And honour not his father or his mother, he shall be free. Thus have ye made the commandment of G...
  [Mrk 7:13]  λόγον  …  θεοῦ  (dist: 2)
    Making the word of God of none effect through your tradition, which ye have delivered: and many s...
  [Luk 5:1]  λόγον  …  θεοῦ  (dist: 2)
    And it came to pass, that, as the people pressed upon him to hear the word of God, he stood by th...
  [Luk 8:11]  λόγος  …  θεοῦ.  (dist: 2)
    Now the parable is this: The seed is the word of God.
  [Luk 8:21]  λόγον  …  θεοῦ  (dist: 2)
    And he answered and said unto them, My mother and my brethren are these which hear the word of Go...
  [Luk 11:28]  λόγον  …  θεοῦ  (dist: 2)
    But he said, Yea rather, blessed are they that hear the word of God, and keep it.
  [Luk 24:19]  λόγῳ  …  θεοῦ  (dist: 3)
    And he said unto them, What things? And they said unto him, Concerning Jesus of Nazareth, which w...
  [Jhn 1:1]  λόγος.  …  θεὸς  (dist: 3)
    In the beginning was the Word, and the Word was with God, and the Word was God.
  [Jhn 1:1]  λόγος  …  θεόν,  (dist: 4)
    In the beginning was the Word, and the Word was with God, and the Word was God.
  [Jhn 1:14]  λόγος (Jhn 1:14)  …  θεοῦ (Jhn 1:13)  (dist: 4)
    And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the on...
  [Luk 9:28]  λόγους (Luk 9:28)  …  θεοῦ.¶ (Luk 9:27)  (dist: 5)
    And it came to pass about an eight days after these sayings, he took Peter and John and James, an...
  [Luk 12:10]  λόγον (Luk 12:10)  …  θεοῦ. (Luk 12:9)  (dist: 5)
    And whosoever shall speak a word against the Son of man, it shall be forgiven him: but unto him t...
  [Jhn 1:1]  λόγος, (Jhn 1:1)  …  θεόν. (Luk 24:53)  (dist: 6)
    In the beginning was the Word, and the Word was with God, and the Word was God.
  [Luk 7:17]  λόγος (Luk 7:17)  …  θεὸς (Luk 7:16)  (dist: 7)
    And this rumour of him went forth throughout all Judea, and throughout all the region round about.
  [Mrk 10:24]  λόγοις (Mrk 10:24)  …  θεοῦ (Mrk 10:23)  (dist: 8)
    And the disciples were astonished at his words. But Jesus answereth again, and saith unto them, C...

---
## 7. Collocation Statistics

Find words that co-occur with a target root significantly more often than chance predicts.
Scored by **PMI** (Pointwise Mutual Information) and **G²** (log-likelihood ratio).
G² is more reliable for rare words; PMI highlights surprisingly specific pairings.

In [24]:
from bible_grammar.collocation import print_collocations

# What clusters around רוּחַ (spirit/wind) in the OT?
print_collocations('H7307', window=5, corpus='OT')

══════════════════════════════════════════════════════════════════════
  Collocations: רוּחַ  (H7307)
  Window: ±5 words  |  Corpus: OT  |  Min count: 3
══════════════════════════════════════════════════════════════════════

  Target frequency : 378 / 305,652 tokens

  Strongs   Lemma                  Gloss                       Obs    Exp    PMI        G²
  -------- --------------------- ------------------------ ----- ------ ------  --------
  H6921     קָדִים                 east                         16    0.8   4.23      67.8  ███
  H7469     רְעוּת                 longing                       7    0.1   6.34      61.6  ███
  H5397     נִשְׁמָא               breath                       10    0.3   5.07      55.9  ██
  H7070     קָנֶה                  branch                       13    0.8   4.08      52.2  ██
  H5012     נָבָא                  to prophesy                  15    1.4   3.40      45.7  ██
  H1121     בֵּן                   son: child                   19   61.1  -1.69      45.6  ██
  H2219     זָרָה                  to scatter                   10    0.5   4.37      44.4  ██
  H6470     פָּעַם                 to trouble                    5    0.1   6.34      44.0  ██
  H5591     סַ֫עַר                 tempest                       8    0.3   4.75      40.3  ██
  H1892     הֶ֫בֶל                 vanity                       11    0.9   3.61      36.6  █
  H5218     נָכָא                  stricken                      4    0.1   6.34      35.2  █
  H4671     מוֹץ                   chaff                         5    0.1   5.66      33.5  █
  H6743     צָלַח                  to rush                       9    0.8   3.48      28.4  █
  H853      אֵת                    [Obj.]                       88  135.4  -0.62      27.9  █
  H212      אוֹפָן                 wheel                         7    0.4   4.02      27.3  █
  H7130     קֶ֫רֶב                 entrails: among              15    2.8   2.42      27.0  █
  H1847     דַּ֫עַת                knowledge                    10    1.1   3.14      26.9  █
  H1793     דַּכָּא                contrite                      3    0.0   6.34      26.4  █
  H3001     יָבֵשׁ                 to wither                     8    0.7   3.45      24.9  █
  H3820     בָּל                   mind                         24    7.4   1.71      24.7  █

In [25]:
# What clusters around λόγος (word) in the NT?
print_collocations('G3056', window=5, corpus='NT')

══════════════════════════════════════════════════════════════════════
  Collocations: λόγος  (G3056)
  Window: ±5 words  |  Corpus: NT  |  Min count: 3
══════════════════════════════════════════════════════════════════════

  Target frequency : 332 / 141,746 tokens

  Strongs   Lemma                  Gloss                       Obs    Exp    PMI        G²
  -------- --------------------- ------------------------ ----- ------ ------  --------
  G3588     ὁ                      the/this/who                638  485.0   0.40     351.3  ████████████
  G191      ἀκούω                  to hear                      44   10.2   2.11      67.6  ███
  G5083     τηρέω                  to keep: observe             15    1.7   3.13      41.8  ██
  G3778     οὗτος                  this/he/she/it               68   33.4   1.03      32.6  █
  G4687     σπείρω                 to sow                       11    1.2   3.17      31.2  █
  G1223     διά                    through/because of           40   16.0   1.32      28.1  █
  G2316     θεός                   God                          62   31.5   0.98      27.0  █
  G4932     συντέμνω               to cut short                  3    0.1   6.00      25.0  █
  G1722     ἐν                     in/on/among                 100   66.4   0.59      19.6
  G2980     λαλέω                  to speak                     21    7.0   1.59      19.5
  G2727     κατηχέω                to instruct                   4    0.2   4.42      19.2
  G4103     πιστός                 faithful                      9    1.6   2.50      17.4
  G4394     προφητεία              prophecy                      5    0.5   3.49      16.4
  G1209     δέχομαι                to receive                    8    1.3   2.58      16.3
  G3928     παρέρχομαι             to pass by                    6    0.7   3.09      16.2
  G846      αὐτός                  it/s/he                     103  137.3  -0.41      15.3
  G975      βιβλίον                scroll                        6    0.8   2.87      14.4
  G4678     σοφία                  wisdom                        7    1.2   2.55      14.0
  G3165                                                         71   47.5   0.58      12.3
  G2605     καταγγέλλω             to proclaim                   4    0.4   3.33      12.1

In [26]:
# Return raw DataFrame for further analysis
from bible_grammar.collocation import collocations

df = collocations('H1285', window=5, corpus='OT', min_count=3)  # בְּרִית covenant
df[['strongs', 'lemma', 'gloss', 'co_count', 'expected', 'pmi', 'log_likelihood']].head(15)

   strongs    lemma              gloss  co_count  expected   pmi  log_likelihood
0    H3772   כָּרַת        to cut: cut        84      2.68  4.97           468.3
1     H727   אֲרוֹן                ark        46      1.88  4.62           223.9
2     H854      אֵת               with        69      8.63  3.00           184.5
3    H6565    פּוּר           to break        22      0.46  5.57           139.5
4    H5769   עוֹלָם  forever: enduring        33      4.07  3.02            85.3
5     H423    אָלָה               oath        10      0.33  4.94            52.5
6    H8104   שָׁמַר      to keep: obey        26      4.36  2.58            52.3
7    H2142    זָכַר        to remember        19      2.16  3.14            51.3
8     H853      אֵת             [Obj.]       158    101.71  0.64            46.4
9     H430                                    57     24.19  1.24            36.9
10   H3068  אֲדֹנָי               Lord       103     60.66  0.76            33.3
11   H6965     קוּם     to arise: rise        22      5.84  1.91            27.4
12   H2233   זֶ֫רַע               seed        13      2.13  2.61            26.3
13   H2617   חֶ֫סֶד           kindness        13      2.30  2.50            24.6
14   H3327  יִצְחָק              Isaac         9      1.00  3.16            24.3

---
## 8. Morphological Distribution Charts

Visualise how a root's grammatical forms distribute across books.

- **Hebrew verbs:** stem × conjugation (Qal Perfect, Piel Imperfect, …)
- **Greek verbs:** tense × voice (Aorist Active, Present Passive, …)
- **Greek nouns:** case distribution (Nominative, Accusative, Genitive, Dative)

In [27]:
from bible_grammar.morph_chart import print_morph_distribution

# H1696 דָבַר — almost entirely Piel, but the distribution shifts by genre
print_morph_distribution('H1696')

══════════════════════════════════════════════════════════════════════
  Morphological Distribution: H1696  —  דָבַר  (to speak: speak)
══════════════════════════════════════════════════════════════════════

  Book                                  Qal Participle        Qal Participle passive                Niphal Perfect             Niphal Participle                  Piel Perfect      Piel Consecutive Perfect                Piel Imperfect    Piel Consecutive Imperfect                  Piel Jussive               Piel Imperative     Piel Infinitive construct               Piel Participle                        Piel u       Pual Participle passive           Hithpael Participle    Hiphil Consecutive Perfect                Hiphil Jussive
  ----------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------
  Genesis                                       1    1%                                                                                                                 25   36%                       21   30%                        4    6%                                                                                    2    3%                       13   19%                        3    4%                                                                                                                                                         [69]
  Exodus                                        1    1%                                                                                                                 22   27%                       21   26%                       11   13%                        7    9%                        1    1%                       10   12%                        8   10%                        1    1%                                                                                                                                                         [82]
  Leviticus                                                                                                                                                             3    5%                       40   61%                        2    3%                                                                                   21   32%                                                                                                                                                                                                                     [66]
  Numbers                                       3    3%                                                                                                                 18   15%                       60   50%                       14   12%                        3    3%                                                     14   12%                        6    5%                                                                                                                  1    1%                                                               [119]
  Deuteronomy                                   1    2%                                                                                                                 34   52%                        8   12%                        6    9%                        5    8%                                                                                   10   15%                        2    3%                                                                                                                                                         [66]
  Joshua                                                                                                                                                               21   66%                        6   19%                        1    3%                        1    3%                                                      1    3%                        1    3%                        1    3%                                                                                                                                                         [32]
  Judges                                                                                                                                                                6   23%                        8   31%                        1    4%                                                                                    4   15%                        6   23%                        1    4%                                                                                                                                                         [26]
  Ruth                                                                                                                                                                  2   67%                                                                                                                                                                              1   33%                                                                                                                                                                                       [3]
  1 Samuel                                                                                                                                                             15   38%                       11   28%                        3    8%                                                                                    4   10%                        3    8%                        2    5%                        1    3%                                                                                                                           [39]
  2 Samuel                                                                                                                                                             12   32%                        4   11%                        4   11%                        2    5%                                                      5   13%                       10   26%                        1    3%                                                                                                                                                         [38]
  1 Kings                                                                                                                                                              42   55%                       17   22%                        6    8%                        4    5%                                                      3    4%                        2    3%                        3    4%                                                                                                                                                         [77]
  2 Kings                                                                                                                                                              24   48%                       15   30%                        1    2%                        1    2%                        1    2%                        2    4%                        4    8%                        2    4%                                                                                                                                                         [50]
  1 Chronicles                                                                                                                                                          6   60%                        3   30%                                                      1   10%                                                                                                                                                                                                                                                                                 [10]
  2 Chronicles                                                                                                                                                         15   45%                       12   36%                        2    6%                        2    6%                                                                                    1    3%                        1    3%                                                                                                                                                         [33]
  Nehemiah                                                                                                                                                              1   25%                                                                                                                                                                              2   50%                        1   25%                                                                                                                                                         [4]
  Esther                                        1   14%                                                                                                                  3   43%                        1   14%                                                                                                                                                                              2   29%                                                                                                                                                         [7]
  Job                                           1    3%                                                                                                                  6   16%                        1    3%                       16   42%                                                                                    2    5%                        9   24%                        3    8%                                                                                                                                                         [38]
  Psalms                                        8   14%                                                      1    2%                                                     12   21%                        1    2%                       23   40%                        1    2%                                                                                    6   11%                        1    2%                        1    2%                        1    2%                                                      1    2%                        1    2%   [57]
  Proverbs                                      1   10%                        1   10%                                                                                                                                                5   50%                                                      1   10%                                                      1   10%                        1   10%                                                                                                                                                         [10]
  Ecclesiastes                                                                                                                                                          1   20%                                                      1   20%                        1   20%                                                                                    2   40%                                                                                                                                                                                       [5]
  Isaiah                                        3    6%                                                                                                                 21   43%                                                      5   10%                                                      1    2%                        4    8%                       10   20%                        4    8%                        1    2%                                                                                                                           [49]
  Jeremiah                                      4    4%                                                                                                                 55   50%                        9    8%                       18   16%                        7    6%                                                      1    1%                       14   13%                        3    3%                                                                                                                                                         [111]
  Ezekiel                                                                                                                                 1    2%                       29   45%                        6    9%                        7   11%                        5    8%                                                      9   14%                        1    2%                        3    5%                        2    3%                                                      1    2%                                                               [64]
  Daniel                                        1    7%                                                                                                                  2   14%                        3   21%                        3   21%                                                                                                                  1    7%                        4   29%                                                                                                                                                         [14]
  Hosea                                                                                                                                                                 3   43%                                                      1   14%                        2   29%                                                                                    1   14%                                                                                                                                                                                       [7]
  Amos                                          1   33%                                                                                                                  2   67%                                                                                                                                                                                                                                                                                                                                                                           [3]
  Micah                                         1   33%                                                                                                                  2   67%                                                                                                                                                                                                                                                                                                                                                                           [3]
  Zechariah                                    11   61%                                                                                                                  2   11%                        1    6%                        1    6%                        1    6%                                                      2   11%                                                                                                                                                                                                                     [18]

In [28]:
# G3056 λόγος — case distribution across NT books
print_morph_distribution('G3056')

══════════════════════════════════════════════════════════════════════
  Morphological Distribution: G3056  —  λόγος  (word)
══════════════════════════════════════════════════════════════════════

  Book                      Nominative    Accusative      Genitive        Dative
  ----------------------  ------------  ------------  ------------  ------------
  Matthew                       3    9%       24   73%        3    9%        3    9%   [33]
  Mark                          2    8%       19   79%                      3   12%   [24]
  Luke                          8   25%       13   41%        5   16%        6   19%   [32]
  John                         17   42%       16   40%        4   10%        3    8%   [40]
  Acts                         10   15%       35   54%        9   14%       11   17%   [65]
  Romans                        2   25%        3   38%                      3   38%   [8]
  1 Corinthians                 6   35%        4   24%        2   12%        5   29%   [17]
  2 Corinthians                 2   22%        3   33%                      4   44%   [9]
  Ephesians                     2   50%        1   25%                      1   25%   [4]
  Philippians                                 4  100%                               [4]
  Colossians                    2   29%        2   29%        1   14%        2   29%   [7]
  1 Thessalonians               1   11%        4   44%                      4   44%   [9]
  2 Thessalonians               1   20%                      2   40%        2   40%   [5]
  1 Timothy                     3   38%                      1   12%        4   50%   [8]
  2 Timothy                     3   43%        2   29%        1   14%        1   14%   [7]
  Titus                         2   40%        2   40%        1   20%                 [5]
  Hebrews                       6   50%        4   33%        2   17%                 [12]
  James                                       1   20%        2   40%        2   40%   [5]
  1 Peter                                     2   33%        2   33%        2   33%   [6]
  2 Peter                                     1   25%                      3   75%   [4]
  1 John                        4   57%        1   14%        1   14%        1   14%   [7]
  Revelation                    5   28%       12   67%        1    6%                 [18]

In [29]:
# Save stacked bar chart to PNG
from bible_grammar.morph_chart import morph_chart

morph_chart('H1696', output_path='../../../output/charts/ot/lexicon/dabar-morph.png')
morph_chart('G3056', output_path='../../../output/charts/nt/lexicon/logos-case.png')

  Saved: ../output/charts/dabar-morph.png

  Saved: ../output/charts/logos-case.png

---
## Quick Reference — All Modules

```python
from bible_grammar import (
    # Core query
    query, translation_query,

    # Word-level analysis
    word_study, print_word_study, resolve_strongs,
    concordance, lemma_frequency, top_lemmas,

    # Cross-language analysis
    translation_equivalents_w, hebrew_sources_w,
    lxx_consistency, print_lxx_consistency,
    consistency_heatmap, batch_consistency,

    # Semantic analysis
    semantic_profile, print_semantic_profile, save_semantic_profile,
    compare_synonyms, print_synonym_comparison, synonym_table,
    collocations, print_collocations, collocation_network,

    # Morphological analysis
    morph_distribution, print_morph_distribution, morph_chart,

    # Textual / intertextual
    phrase_search, proximity_search,
    nt_quotations, verse_comparison,
    quotation_align, print_quotation_align, batch_align,
    term_map, print_term_map, THEOLOGICAL_TERMS,
    parallel_passage, print_parallel,

    # Reporting
    book_profile, print_profile, batch_profiles,
    hapax_legomena, hapax_summary,
    freq_table,
)
```

**Slash commands** (Claude Code): `/word-study`, `/synonym`, `/lxx-consistency`,
`/term-map`, `/phrase-search`, `/collocations`, `/morph-chart`, `/semantic-profile`